// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/analytics (interfaces: Usecase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_usecase.go -package=mocks parkir-pintar/internal/analytics Usecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "parkir-pintar/internal/analytics/model"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetIdleHours mocks base method.
func (m *MockUsecase) GetIdleHours(ctx context.Context) ([]model.PeakHourStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdleHours", ctx)
	ret0, _ := ret[0].([]model.PeakHourStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdleHours indicates an expected call of GetIdleHours.
func (mr *MockUsecaseMockRecorder) GetIdleHours(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdleHours", reflect.TypeOf((*MockUsecase)(nil).GetIdleHours), ctx)
}

// GetPeakHours mocks base method.
func (m *MockUsecase) GetPeakHours(ctx context.Context) ([]model.PeakHourStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeakHours", ctx)
	ret0, _ := ret[0].([]model.PeakHourStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeakHours indicates an expected call of GetPeakHours.
func (mr *MockUsecaseMockRecorder) GetPeakHours(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeakHours", reflect.TypeOf((*MockUsecase)(nil).GetPeakHours), ctx)
}

// GetUsagePatterns mocks base method.
func (m *MockUsecase) GetUsagePatterns(ctx context.Context) (*model.UsagePattern, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsagePatterns", ctx)
	ret0, _ := ret[0].(*model.UsagePattern)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsagePatterns indicates an expected call of GetUsagePatterns.
func (mr *MockUsecaseMockRecorder) GetUsagePatterns(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsagePatterns", reflect.TypeOf((*MockUsecase)(nil).GetUsagePatterns), ctx)
}

// PredictResources mocks base method.
func (m *MockUsecase) PredictResources(ctx context.Context, horizon time.Duration) ([]model.ResourcePrediction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PredictResources", ctx, horizon)
	ret0, _ := ret[0].([]model.ResourcePrediction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PredictResources indicates an expected call of PredictResources.
func (mr *MockUsecaseMockRecorder) PredictResources(ctx, horizon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PredictResources", reflect.TypeOf((*MockUsecase)(nil).PredictResources), ctx, horizon)
}

// RecordEvent mocks base method.
func (m *MockUsecase) RecordEvent(ctx context.Context, event model.ReservationEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordEvent indicates an expected call of RecordEvent.
func (mr *MockUsecaseMockRecorder) RecordEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordEvent", reflect.TypeOf((*MockUsecase)(nil).RecordEvent), ctx, event)
}
