// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/analytics (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repository.go -package=mocks parkir-pintar/internal/analytics Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "parkir-pintar/internal/analytics/model"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetDailyOccupancy mocks base method.
func (m *MockRepository) GetDailyOccupancy(ctx context.Context, days int) ([]model.DailyOccupancy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyOccupancy", ctx, days)
	ret0, _ := ret[0].([]model.DailyOccupancy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyOccupancy indicates an expected call of GetDailyOccupancy.
func (mr *MockRepositoryMockRecorder) GetDailyOccupancy(ctx, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyOccupancy", reflect.TypeOf((*MockRepository)(nil).GetDailyOccupancy), ctx, days)
}

// GetHourlyStats mocks base method.
func (m *MockRepository) GetHourlyStats(ctx context.Context, startDate, endDate time.Time) ([]model.PeakHourStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHourlyStats", ctx, startDate, endDate)
	ret0, _ := ret[0].([]model.PeakHourStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHourlyStats indicates an expected call of GetHourlyStats.
func (mr *MockRepositoryMockRecorder) GetHourlyStats(ctx, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHourlyStats", reflect.TypeOf((*MockRepository)(nil).GetHourlyStats), ctx, startDate, endDate)
}

// RecordEvent mocks base method.
func (m *MockRepository) RecordEvent(ctx context.Context, event model.ReservationEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordEvent indicates an expected call of RecordEvent.
func (mr *MockRepositoryMockRecorder) RecordEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordEvent", reflect.TypeOf((*MockRepository)(nil).RecordEvent), ctx, event)
}
