// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: reservation/v1/reservation.proto

package reservationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReservationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DriverId       string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	VehicleType    string                 `protobuf:"bytes,2,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`          // "car" or "motorcycle"
	AssignmentMode string                 `protobuf:"bytes,3,opt,name=assignment_mode,json=assignmentMode,proto3" json:"assignment_mode,omitempty"` // "system_assigned" or "user_selected"
	SpotId         string                 `protobuf:"bytes,4,opt,name=spot_id,json=spotId,proto3" json:"spot_id,omitempty"`                         // required only for user_selected
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReservationRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *CreateReservationRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *CreateReservationRequest) GetAssignmentMode() string {
	if x != nil {
		return x.AssignmentMode
	}
	return ""
}

func (x *CreateReservationRequest) GetSpotId() string {
	if x != nil {
		return x.SpotId
	}
	return ""
}

func (x *CreateReservationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationRequest) Reset() {
	*x = GetReservationRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationRequest) ProtoMessage() {}

func (x *GetReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationRequest.ProtoReflect.Descriptor instead.
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *GetReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *CancelReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type CheckInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{3}
}

func (x *CheckInRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type CheckOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOutRequest) Reset() {
	*x = CheckOutRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutRequest) ProtoMessage() {}

func (x *CheckOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutRequest.ProtoReflect.Descriptor instead.
func (*CheckOutRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{4}
}

func (x *CheckOutRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ConfirmReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationRequest) Reset() {
	*x = ConfirmReservationRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationRequest) ProtoMessage() {}

func (x *ConfirmReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type CompleteCheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteCheckoutRequest) Reset() {
	*x = CompleteCheckoutRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteCheckoutRequest) ProtoMessage() {}

func (x *CompleteCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteCheckoutRequest.ProtoReflect.Descriptor instead.
func (*CompleteCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteCheckoutRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ExpireReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireReservationRequest) Reset() {
	*x = ExpireReservationRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireReservationRequest) ProtoMessage() {}

func (x *ExpireReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireReservationRequest.ProtoReflect.Descriptor instead.
func (*ExpireReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{7}
}

func (x *ExpireReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ReservationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DriverId       string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	SpotId         string                 `protobuf:"bytes,3,opt,name=spot_id,json=spotId,proto3" json:"spot_id,omitempty"`
	VehicleType    string                 `protobuf:"bytes,4,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	AssignmentMode string                 `protobuf:"bytes,5,opt,name=assignment_mode,json=assignmentMode,proto3" json:"assignment_mode,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ConfirmedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CheckedInAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=checked_in_at,json=checkedInAt,proto3" json:"checked_in_at,omitempty"`
	CheckedOutAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=checked_out_at,json=checkedOutAt,proto3" json:"checked_out_at,omitempty"`
	CancelledAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReservationResponse) Reset() {
	*x = ReservationResponse{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationResponse) ProtoMessage() {}

func (x *ReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationResponse.ProtoReflect.Descriptor instead.
func (*ReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{8}
}

func (x *ReservationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReservationResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ReservationResponse) GetSpotId() string {
	if x != nil {
		return x.SpotId
	}
	return ""
}

func (x *ReservationResponse) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *ReservationResponse) GetAssignmentMode() string {
	if x != nil {
		return x.AssignmentMode
	}
	return ""
}

func (x *ReservationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReservationResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReservationResponse) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

func (x *ReservationResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ReservationResponse) GetCheckedInAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedInAt
	}
	return nil
}

func (x *ReservationResponse) GetCheckedOutAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedOutAt
	}
	return nil
}

func (x *ReservationResponse) GetCancelledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CancelledAt
	}
	return nil
}

type ListByDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // optional filter, empty = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByDriverRequest) Reset() {
	*x = ListByDriverRequest{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByDriverRequest) ProtoMessage() {}

func (x *ListByDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByDriverRequest.ProtoReflect.Descriptor instead.
func (*ListByDriverRequest) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{9}
}

func (x *ListByDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ListByDriverRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListByDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*ReservationResponse `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByDriverResponse) Reset() {
	*x = ListByDriverResponse{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByDriverResponse) ProtoMessage() {}

func (x *ListByDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByDriverResponse.ProtoReflect.Descriptor instead.
func (*ListByDriverResponse) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{10}
}

func (x *ListByDriverResponse) GetReservations() []*ReservationResponse {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type CheckOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *ReservationResponse   `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	BillingId     string                 `protobuf:"bytes,3,opt,name=billing_id,json=billingId,proto3" json:"billing_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,4,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	BookingFee    int64                  `protobuf:"varint,5,opt,name=booking_fee,json=bookingFee,proto3" json:"booking_fee,omitempty"`
	ParkingFee    int64                  `protobuf:"varint,6,opt,name=parking_fee,json=parkingFee,proto3" json:"parking_fee,omitempty"`
	OvernightFee  int64                  `protobuf:"varint,7,opt,name=overnight_fee,json=overnightFee,proto3" json:"overnight_fee,omitempty"`
	PenaltyAmount int64                  `protobuf:"varint,8,opt,name=penalty_amount,json=penaltyAmount,proto3" json:"penalty_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOutResponse) Reset() {
	*x = CheckOutResponse{}
	mi := &file_reservation_v1_reservation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutResponse) ProtoMessage() {}

func (x *CheckOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_v1_reservation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutResponse.ProtoReflect.Descriptor instead.
func (*CheckOutResponse) Descriptor() ([]byte, []int) {
	return file_reservation_v1_reservation_proto_rawDescGZIP(), []int{11}
}

func (x *CheckOutResponse) GetReservation() *ReservationResponse {
	if x != nil {
		return x.Reservation
	}
	return nil
}

func (x *CheckOutResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CheckOutResponse) GetBillingId() string {
	if x != nil {
		return x.BillingId
	}
	return ""
}

func (x *CheckOutResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CheckOutResponse) GetBookingFee() int64 {
	if x != nil {
		return x.BookingFee
	}
	return 0
}

func (x *CheckOutResponse) GetParkingFee() int64 {
	if x != nil {
		return x.ParkingFee
	}
	return 0
}

func (x *CheckOutResponse) GetOvernightFee() int64 {
	if x != nil {
		return x.OvernightFee
	}
	return 0
}

func (x *CheckOutResponse) GetPenaltyAmount() int64 {
	if x != nil {
		return x.PenaltyAmount
	}
	return 0
}

var File_reservation_v1_reservation_proto protoreflect.FileDescriptor

const file_reservation_v1_reservation_proto_rawDesc = "" +
	"\n" +
	" reservation/v1/reservation.proto\x12\x0ereservation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x01\n" +
	"\x18CreateReservationRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12!\n" +
	"\fvehicle_type\x18\x02 \x01(\tR\vvehicleType\x12'\n" +
	"\x0fassignment_mode\x18\x03 \x01(\tR\x0eassignmentMode\x12\x17\n" +
	"\aspot_id\x18\x04 \x01(\tR\x06spotId\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\">\n" +
	"\x15GetReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"A\n" +
	"\x18CancelReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"7\n" +
	"\x0eCheckInRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"8\n" +
	"\x0fCheckOutRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"B\n" +
	"\x19ConfirmReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"@\n" +
	"\x17CompleteCheckoutRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"A\n" +
	"\x18ExpireReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"\xa3\x04\n" +
	"\x13ReservationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x17\n" +
	"\aspot_id\x18\x03 \x01(\tR\x06spotId\x12!\n" +
	"\fvehicle_type\x18\x04 \x01(\tR\vvehicleType\x12'\n" +
	"\x0fassignment_mode\x18\x05 \x01(\tR\x0eassignmentMode\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x12=\n" +
	"\fconfirmed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAt\x129\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12>\n" +
	"\rchecked_in_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcheckedInAt\x12@\n" +
	"\x0echecked_out_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\fcheckedOutAt\x12=\n" +
	"\fcancelled_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vcancelledAt\"J\n" +
	"\x13ListByDriverRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"_\n" +
	"\x14ListByDriverResponse\x12G\n" +
	"\freservations\x18\x01 \x03(\v2#.reservation.v1.ReservationResponseR\freservations\"\xc8\x02\n" +
	"\x10CheckOutResponse\x12E\n" +
	"\vreservation\x18\x01 \x01(\v2#.reservation.v1.ReservationResponseR\vreservation\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x03R\vtotalAmount\x12\x1d\n" +
	"\n" +
	"billing_id\x18\x03 \x01(\tR\tbillingId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x04 \x01(\tR\tpaymentId\x12\x1f\n" +
	"\vbooking_fee\x18\x05 \x01(\x03R\n" +
	"bookingFee\x12\x1f\n" +
	"\vparking_fee\x18\x06 \x01(\x03R\n" +
	"parkingFee\x12#\n" +
	"\rovernight_fee\x18\a \x01(\x03R\fovernightFee\x12%\n" +
	"\x0epenalty_amount\x18\b \x01(\x03R\rpenaltyAmount2\xdd\x06\n" +
	"\x12ReservationService\x12b\n" +
	"\x11CreateReservation\x12(.reservation.v1.CreateReservationRequest\x1a#.reservation.v1.ReservationResponse\x12\\\n" +
	"\x0eGetReservation\x12%.reservation.v1.GetReservationRequest\x1a#.reservation.v1.ReservationResponse\x12b\n" +
	"\x11CancelReservation\x12(.reservation.v1.CancelReservationRequest\x1a#.reservation.v1.ReservationResponse\x12N\n" +
	"\aCheckIn\x12\x1e.reservation.v1.CheckInRequest\x1a#.reservation.v1.ReservationResponse\x12M\n" +
	"\bCheckOut\x12\x1f.reservation.v1.CheckOutRequest\x1a .reservation.v1.CheckOutResponse\x12d\n" +
	"\x12ConfirmReservation\x12).reservation.v1.ConfirmReservationRequest\x1a#.reservation.v1.ReservationResponse\x12]\n" +
	"\x10CompleteCheckout\x12'.reservation.v1.CompleteCheckoutRequest\x1a .reservation.v1.CheckOutResponse\x12b\n" +
	"\x11ExpireReservation\x12(.reservation.v1.ExpireReservationRequest\x1a#.reservation.v1.ReservationResponse\x12Y\n" +
	"\fListByDriver\x12#.reservation.v1.ListByDriverRequest\x1a$.reservation.v1.ListByDriverResponseB2Z0parkir-pintar/proto/reservation/v1;reservationv1b\x06proto3"

var (
	file_reservation_v1_reservation_proto_rawDescOnce sync.Once
	file_reservation_v1_reservation_proto_rawDescData []byte
)

func file_reservation_v1_reservation_proto_rawDescGZIP() []byte {
	file_reservation_v1_reservation_proto_rawDescOnce.Do(func() {
		file_reservation_v1_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reservation_v1_reservation_proto_rawDesc), len(file_reservation_v1_reservation_proto_rawDesc)))
	})
	return file_reservation_v1_reservation_proto_rawDescData
}

var file_reservation_v1_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_reservation_v1_reservation_proto_goTypes = []any{
	(*CreateReservationRequest)(nil),  // 0: reservation.v1.CreateReservationRequest
	(*GetReservationRequest)(nil),     // 1: reservation.v1.GetReservationRequest
	(*CancelReservationRequest)(nil),  // 2: reservation.v1.CancelReservationRequest
	(*CheckInRequest)(nil),            // 3: reservation.v1.CheckInRequest
	(*CheckOutRequest)(nil),           // 4: reservation.v1.CheckOutRequest
	(*ConfirmReservationRequest)(nil), // 5: reservation.v1.ConfirmReservationRequest
	(*CompleteCheckoutRequest)(nil),   // 6: reservation.v1.CompleteCheckoutRequest
	(*ExpireReservationRequest)(nil),  // 7: reservation.v1.ExpireReservationRequest
	(*ReservationResponse)(nil),       // 8: reservation.v1.ReservationResponse
	(*ListByDriverRequest)(nil),       // 9: reservation.v1.ListByDriverRequest
	(*ListByDriverResponse)(nil),      // 10: reservation.v1.ListByDriverResponse
	(*CheckOutResponse)(nil),          // 11: reservation.v1.CheckOutResponse
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
}
var file_reservation_v1_reservation_proto_depIdxs = []int32{
	12, // 0: reservation.v1.ReservationResponse.confirmed_at:type_name -> google.protobuf.Timestamp
	12, // 1: reservation.v1.ReservationResponse.expires_at:type_name -> google.protobuf.Timestamp
	12, // 2: reservation.v1.ReservationResponse.checked_in_at:type_name -> google.protobuf.Timestamp
	12, // 3: reservation.v1.ReservationResponse.checked_out_at:type_name -> google.protobuf.Timestamp
	12, // 4: reservation.v1.ReservationResponse.cancelled_at:type_name -> google.protobuf.Timestamp
	8,  // 5: reservation.v1.ListByDriverResponse.reservations:type_name -> reservation.v1.ReservationResponse
	8,  // 6: reservation.v1.CheckOutResponse.reservation:type_name -> reservation.v1.ReservationResponse
	0,  // 7: reservation.v1.ReservationService.CreateReservation:input_type -> reservation.v1.CreateReservationRequest
	1,  // 8: reservation.v1.ReservationService.GetReservation:input_type -> reservation.v1.GetReservationRequest
	2,  // 9: reservation.v1.ReservationService.CancelReservation:input_type -> reservation.v1.CancelReservationRequest
	3,  // 10: reservation.v1.ReservationService.CheckIn:input_type -> reservation.v1.CheckInRequest
	4,  // 11: reservation.v1.ReservationService.CheckOut:input_type -> reservation.v1.CheckOutRequest
	5,  // 12: reservation.v1.ReservationService.ConfirmReservation:input_type -> reservation.v1.ConfirmReservationRequest
	6,  // 13: reservation.v1.ReservationService.CompleteCheckout:input_type -> reservation.v1.CompleteCheckoutRequest
	7,  // 14: reservation.v1.ReservationService.ExpireReservation:input_type -> reservation.v1.ExpireReservationRequest
	9,  // 15: reservation.v1.ReservationService.ListByDriver:input_type -> reservation.v1.ListByDriverRequest
	8,  // 16: reservation.v1.ReservationService.CreateReservation:output_type -> reservation.v1.ReservationResponse
	8,  // 17: reservation.v1.ReservationService.GetReservation:output_type -> reservation.v1.ReservationResponse
	8,  // 18: reservation.v1.ReservationService.CancelReservation:output_type -> reservation.v1.ReservationResponse
	8,  // 19: reservation.v1.ReservationService.CheckIn:output_type -> reservation.v1.ReservationResponse
	11, // 20: reservation.v1.ReservationService.CheckOut:output_type -> reservation.v1.CheckOutResponse
	8,  // 21: reservation.v1.ReservationService.ConfirmReservation:output_type -> reservation.v1.ReservationResponse
	11, // 22: reservation.v1.ReservationService.CompleteCheckout:output_type -> reservation.v1.CheckOutResponse
	8,  // 23: reservation.v1.ReservationService.ExpireReservation:output_type -> reservation.v1.ReservationResponse
	10, // 24: reservation.v1.ReservationService.ListByDriver:output_type -> reservation.v1.ListByDriverResponse
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_reservation_v1_reservation_proto_init() }
func file_reservation_v1_reservation_proto_init() {
	if File_reservation_v1_reservation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reservation_v1_reservation_proto_rawDesc), len(file_reservation_v1_reservation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reservation_v1_reservation_proto_goTypes,
		DependencyIndexes: file_reservation_v1_reservation_proto_depIdxs,
		MessageInfos:      file_reservation_v1_reservation_proto_msgTypes,
	}.Build()
	File_reservation_v1_reservation_proto = out.File
	file_reservation_v1_reservation_proto_goTypes = nil
	file_reservation_v1_reservation_proto_depIdxs = nil
}
