BEGIN;

DROP SCHEMA IF EXISTS presence CASCADE;
DROP SCHEMA IF EXISTS search CASCADE;
DROP SCHEMA IF EXISTS payment CASCADE;
DROP SCHEMA IF EXISTS billing CASCADE;
DROP SCHEMA IF EXISTS reservation CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp";

COMMIT;
