# SonarCloud / SonarQube configuration
sonar.ci.autoconfig.disabled=true
sonar.organization=piresc-repo
sonar.projectKey=piresc-repo_parkir-pintar
sonar.projectName=parkir-pintar
sonar.sources=.
sonar.qualitygate.wait=true
sonar.go.coverage.reportPaths=coverage.txt
sonar.go.gosec.reportPaths=sonar-gosec.json
sonar.exclusions=frontend/**/*
sonar.coverage.exclusions=**/*_test.go,**/mocks/**/*,**/vendor/**/*,**/*mock*
sonar.cpd.exclusions=**/cmd/**/*.go,**/pkg/**/*.go
sonar.test.inclusions=**/*_test.go
