apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus
    jsonData:
      timeInterval: "15s"

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    uid: tempo
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        tags:
          - key: "service.name"
            value: "service_name"
          - key: "http.method"
            value: "http_method"
          - key: "http.status_code"
            value: "http_status_code"
      tracesToLogs:
        datasourceUid: "loki"
        filterByTraceID: true
        filterBySpanID: false
        tags:
          - key: "service.name"
            value: "service"
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "\"trace_id\":\"(\\w+)\""
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"
