// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/payment (interfaces: Gateway)
//
// Generated by this command:
//
//	mockgen -destination=internal/payment/mocks/mock_payment_gateway.go -package=mocks parkir-pintar/internal/payment Gateway
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
	isgomock struct{}
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// Charge mocks base method.
func (m *MockGateway) Charge(ctx context.Context, amount int64, method string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Charge", ctx, amount, method)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Charge indicates an expected call of Charge.
func (mr *MockGatewayMockRecorder) Charge(ctx, amount, method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Charge", reflect.TypeOf((*MockGateway)(nil).Charge), ctx, amount, method)
}

// GetStatus mocks base method.
func (m *MockGateway) GetStatus(ctx context.Context, transactionRef string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, transactionRef)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockGatewayMockRecorder) GetStatus(ctx, transactionRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockGateway)(nil).GetStatus), ctx, transactionRef)
}

// Refund mocks base method.
func (m *MockGateway) Refund(ctx context.Context, transactionRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refund", ctx, transactionRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refund indicates an expected call of Refund.
func (mr *MockGatewayMockRecorder) Refund(ctx, transactionRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refund", reflect.TypeOf((*MockGateway)(nil).Refund), ctx, transactionRef)
}
