// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/payment/usecase (interfaces: EventPublisher)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_event_publisher.go -package=mocks parkir-pintar/internal/payment/usecase EventPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gateway "parkir-pintar/internal/payment/gateway"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishPaymentFailed mocks base method.
func (m *MockEventPublisher) PublishPaymentFailed(ctx context.Context, event gateway.PaymentResultEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPaymentFailed", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPaymentFailed indicates an expected call of PublishPaymentFailed.
func (mr *MockEventPublisherMockRecorder) PublishPaymentFailed(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPaymentFailed", reflect.TypeOf((*MockEventPublisher)(nil).PublishPaymentFailed), ctx, event)
}

// PublishPaymentSuccess mocks base method.
func (m *MockEventPublisher) PublishPaymentSuccess(ctx context.Context, event gateway.PaymentResultEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPaymentSuccess", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPaymentSuccess indicates an expected call of PublishPaymentSuccess.
func (mr *MockEventPublisherMockRecorder) PublishPaymentSuccess(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPaymentSuccess", reflect.TypeOf((*MockEventPublisher)(nil).PublishPaymentSuccess), ctx, event)
}
