// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: search/v1/search.proto

package searchv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	// GetAvailability returns per-floor availability counts filtered by vehicle type.
	GetAvailability(ctx context.Context, in *GetAvailabilityRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	// GetFloorMap returns the status of every spot on a specific floor.
	GetFloorMap(ctx context.Context, in *GetFloorMapRequest, opts ...grpc.CallOption) (*FloorMapResponse, error)
	// GetSpotDetails returns detailed information for a specific parking spot.
	GetSpotDetails(ctx context.Context, in *GetSpotDetailsRequest, opts ...grpc.CallOption) (*SpotDetailsResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) GetAvailability(ctx context.Context, in *GetAvailabilityRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, "/search.v1.SearchService/GetAvailability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetFloorMap(ctx context.Context, in *GetFloorMapRequest, opts ...grpc.CallOption) (*FloorMapResponse, error) {
	out := new(FloorMapResponse)
	err := c.cc.Invoke(ctx, "/search.v1.SearchService/GetFloorMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetSpotDetails(ctx context.Context, in *GetSpotDetailsRequest, opts ...grpc.CallOption) (*SpotDetailsResponse, error) {
	out := new(SpotDetailsResponse)
	err := c.cc.Invoke(ctx, "/search.v1.SearchService/GetSpotDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility
type SearchServiceServer interface {
	// GetAvailability returns per-floor availability counts filtered by vehicle type.
	GetAvailability(context.Context, *GetAvailabilityRequest) (*AvailabilityResponse, error)
	// GetFloorMap returns the status of every spot on a specific floor.
	GetFloorMap(context.Context, *GetFloorMapRequest) (*FloorMapResponse, error)
	// GetSpotDetails returns detailed information for a specific parking spot.
	GetSpotDetails(context.Context, *GetSpotDetailsRequest) (*SpotDetailsResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (UnimplementedSearchServiceServer) GetAvailability(context.Context, *GetAvailabilityRequest) (*AvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailability not implemented")
}
func (UnimplementedSearchServiceServer) GetFloorMap(context.Context, *GetFloorMapRequest) (*FloorMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFloorMap not implemented")
}
func (UnimplementedSearchServiceServer) GetSpotDetails(context.Context, *GetSpotDetailsRequest) (*SpotDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpotDetails not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_GetAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.v1.SearchService/GetAvailability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetAvailability(ctx, req.(*GetAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetFloorMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFloorMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetFloorMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.v1.SearchService/GetFloorMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetFloorMap(ctx, req.(*GetFloorMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetSpotDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpotDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetSpotDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/search.v1.SearchService/GetSpotDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetSpotDetails(ctx, req.(*GetSpotDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.v1.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailability",
			Handler:    _SearchService_GetAvailability_Handler,
		},
		{
			MethodName: "GetFloorMap",
			Handler:    _SearchService_GetFloorMap_Handler,
		},
		{
			MethodName: "GetSpotDetails",
			Handler:    _SearchService_GetSpotDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search/v1/search.proto",
}
