// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.24.4
// source: search/v1/search.proto

package searchv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchService_GetAvailability_FullMethodName = "/search.v1.SearchService/GetAvailability"
	SearchService_GetFloorMap_FullMethodName     = "/search.v1.SearchService/GetFloorMap"
	SearchService_GetSpotDetails_FullMethodName  = "/search.v1.SearchService/GetSpotDetails"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SearchService provides real-time parking availability queries.
type SearchServiceClient interface {
	// GetAvailability returns per-floor availability counts filtered by vehicle type.
	GetAvailability(ctx context.Context, in *GetAvailabilityRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error)
	// GetFloorMap returns the status of every spot on a specific floor.
	GetFloorMap(ctx context.Context, in *GetFloorMapRequest, opts ...grpc.CallOption) (*FloorMapResponse, error)
	// GetSpotDetails returns detailed information for a specific parking spot.
	GetSpotDetails(ctx context.Context, in *GetSpotDetailsRequest, opts ...grpc.CallOption) (*SpotDetailsResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) GetAvailability(ctx context.Context, in *GetAvailabilityRequest, opts ...grpc.CallOption) (*AvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AvailabilityResponse)
	err := c.cc.Invoke(ctx, SearchService_GetAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetFloorMap(ctx context.Context, in *GetFloorMapRequest, opts ...grpc.CallOption) (*FloorMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FloorMapResponse)
	err := c.cc.Invoke(ctx, SearchService_GetFloorMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) GetSpotDetails(ctx context.Context, in *GetSpotDetailsRequest, opts ...grpc.CallOption) (*SpotDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpotDetailsResponse)
	err := c.cc.Invoke(ctx, SearchService_GetSpotDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility.
//
// SearchService provides real-time parking availability queries.
type SearchServiceServer interface {
	// GetAvailability returns per-floor availability counts filtered by vehicle type.
	GetAvailability(context.Context, *GetAvailabilityRequest) (*AvailabilityResponse, error)
	// GetFloorMap returns the status of every spot on a specific floor.
	GetFloorMap(context.Context, *GetFloorMapRequest) (*FloorMapResponse, error)
	// GetSpotDetails returns detailed information for a specific parking spot.
	GetSpotDetails(context.Context, *GetSpotDetailsRequest) (*SpotDetailsResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) GetAvailability(context.Context, *GetAvailabilityRequest) (*AvailabilityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailability not implemented")
}
func (UnimplementedSearchServiceServer) GetFloorMap(context.Context, *GetFloorMapRequest) (*FloorMapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFloorMap not implemented")
}
func (UnimplementedSearchServiceServer) GetSpotDetails(context.Context, *GetSpotDetailsRequest) (*SpotDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpotDetails not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}
func (UnimplementedSearchServiceServer) testEmbeddedByValue()                       {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	// If the following call panics, it indicates UnimplementedSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_GetAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetAvailability(ctx, req.(*GetAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetFloorMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFloorMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetFloorMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetFloorMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetFloorMap(ctx, req.(*GetFloorMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_GetSpotDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpotDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).GetSpotDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_GetSpotDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).GetSpotDetails(ctx, req.(*GetSpotDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.v1.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailability",
			Handler:    _SearchService_GetAvailability_Handler,
		},
		{
			MethodName: "GetFloorMap",
			Handler:    _SearchService_GetFloorMap_Handler,
		},
		{
			MethodName: "GetSpotDetails",
			Handler:    _SearchService_GetSpotDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search/v1/search.proto",
}
