// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: search/v1/search.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleType   string                 `protobuf:"bytes,1,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"` // "car" or "motorcycle"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailabilityRequest) Reset() {
	*x = GetAvailabilityRequest{}
	mi := &file_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailabilityRequest) ProtoMessage() {}

func (x *GetAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *GetAvailabilityRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

type AvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Floors        []*FloorAvailability   `protobuf:"bytes,1,rep,name=floors,proto3" json:"floors,omitempty"`
	Total         *AvailabilitySummary   `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityResponse) Reset() {
	*x = AvailabilityResponse{}
	mi := &file_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityResponse) ProtoMessage() {}

func (x *AvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityResponse.ProtoReflect.Descriptor instead.
func (*AvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *AvailabilityResponse) GetFloors() []*FloorAvailability {
	if x != nil {
		return x.Floors
	}
	return nil
}

func (x *AvailabilityResponse) GetTotal() *AvailabilitySummary {
	if x != nil {
		return x.Total
	}
	return nil
}

type FloorAvailability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FloorNumber   int32                  `protobuf:"varint,1,opt,name=floor_number,json=floorNumber,proto3" json:"floor_number,omitempty"`
	AvailableCar  int32                  `protobuf:"varint,2,opt,name=available_car,json=availableCar,proto3" json:"available_car,omitempty"`
	AvailableMoto int32                  `protobuf:"varint,3,opt,name=available_moto,json=availableMoto,proto3" json:"available_moto,omitempty"`
	TotalCar      int32                  `protobuf:"varint,4,opt,name=total_car,json=totalCar,proto3" json:"total_car,omitempty"`
	TotalMoto     int32                  `protobuf:"varint,5,opt,name=total_moto,json=totalMoto,proto3" json:"total_moto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloorAvailability) Reset() {
	*x = FloorAvailability{}
	mi := &file_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloorAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloorAvailability) ProtoMessage() {}

func (x *FloorAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloorAvailability.ProtoReflect.Descriptor instead.
func (*FloorAvailability) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *FloorAvailability) GetFloorNumber() int32 {
	if x != nil {
		return x.FloorNumber
	}
	return 0
}

func (x *FloorAvailability) GetAvailableCar() int32 {
	if x != nil {
		return x.AvailableCar
	}
	return 0
}

func (x *FloorAvailability) GetAvailableMoto() int32 {
	if x != nil {
		return x.AvailableMoto
	}
	return 0
}

func (x *FloorAvailability) GetTotalCar() int32 {
	if x != nil {
		return x.TotalCar
	}
	return 0
}

func (x *FloorAvailability) GetTotalMoto() int32 {
	if x != nil {
		return x.TotalMoto
	}
	return 0
}

type AvailabilitySummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalAvailable int32                  `protobuf:"varint,1,opt,name=total_available,json=totalAvailable,proto3" json:"total_available,omitempty"`
	TotalCapacity  int32                  `protobuf:"varint,2,opt,name=total_capacity,json=totalCapacity,proto3" json:"total_capacity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AvailabilitySummary) Reset() {
	*x = AvailabilitySummary{}
	mi := &file_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilitySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilitySummary) ProtoMessage() {}

func (x *AvailabilitySummary) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilitySummary.ProtoReflect.Descriptor instead.
func (*AvailabilitySummary) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *AvailabilitySummary) GetTotalAvailable() int32 {
	if x != nil {
		return x.TotalAvailable
	}
	return 0
}

func (x *AvailabilitySummary) GetTotalCapacity() int32 {
	if x != nil {
		return x.TotalCapacity
	}
	return 0
}

type GetFloorMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FloorNumber   int32                  `protobuf:"varint,1,opt,name=floor_number,json=floorNumber,proto3" json:"floor_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFloorMapRequest) Reset() {
	*x = GetFloorMapRequest{}
	mi := &file_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFloorMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFloorMapRequest) ProtoMessage() {}

func (x *GetFloorMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFloorMapRequest.ProtoReflect.Descriptor instead.
func (*GetFloorMapRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *GetFloorMapRequest) GetFloorNumber() int32 {
	if x != nil {
		return x.FloorNumber
	}
	return 0
}

type FloorMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spots         []*SpotInfo            `protobuf:"bytes,1,rep,name=spots,proto3" json:"spots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloorMapResponse) Reset() {
	*x = FloorMapResponse{}
	mi := &file_search_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloorMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloorMapResponse) ProtoMessage() {}

func (x *FloorMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloorMapResponse.ProtoReflect.Descriptor instead.
func (*FloorMapResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *FloorMapResponse) GetSpots() []*SpotInfo {
	if x != nil {
		return x.Spots
	}
	return nil
}

type SpotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SpotCode      string                 `protobuf:"bytes,2,opt,name=spot_code,json=spotCode,proto3" json:"spot_code,omitempty"`
	VehicleType   string                 `protobuf:"bytes,3,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	FloorNumber   int32                  `protobuf:"varint,5,opt,name=floor_number,json=floorNumber,proto3" json:"floor_number,omitempty"`
	SpotNumber    int32                  `protobuf:"varint,6,opt,name=spot_number,json=spotNumber,proto3" json:"spot_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpotInfo) Reset() {
	*x = SpotInfo{}
	mi := &file_search_v1_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotInfo) ProtoMessage() {}

func (x *SpotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotInfo.ProtoReflect.Descriptor instead.
func (*SpotInfo) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{6}
}

func (x *SpotInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpotInfo) GetSpotCode() string {
	if x != nil {
		return x.SpotCode
	}
	return ""
}

func (x *SpotInfo) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *SpotInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SpotInfo) GetFloorNumber() int32 {
	if x != nil {
		return x.FloorNumber
	}
	return 0
}

func (x *SpotInfo) GetSpotNumber() int32 {
	if x != nil {
		return x.SpotNumber
	}
	return 0
}

type GetSpotDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpotId        string                 `protobuf:"bytes,1,opt,name=spot_id,json=spotId,proto3" json:"spot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpotDetailsRequest) Reset() {
	*x = GetSpotDetailsRequest{}
	mi := &file_search_v1_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpotDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpotDetailsRequest) ProtoMessage() {}

func (x *GetSpotDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpotDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetSpotDetailsRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{7}
}

func (x *GetSpotDetailsRequest) GetSpotId() string {
	if x != nil {
		return x.SpotId
	}
	return ""
}

type SpotDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SpotCode      string                 `protobuf:"bytes,2,opt,name=spot_code,json=spotCode,proto3" json:"spot_code,omitempty"`
	FloorNumber   int32                  `protobuf:"varint,3,opt,name=floor_number,json=floorNumber,proto3" json:"floor_number,omitempty"`
	SpotNumber    int32                  `protobuf:"varint,4,opt,name=spot_number,json=spotNumber,proto3" json:"spot_number,omitempty"`
	VehicleType   string                 `protobuf:"bytes,5,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpotDetailsResponse) Reset() {
	*x = SpotDetailsResponse{}
	mi := &file_search_v1_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpotDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotDetailsResponse) ProtoMessage() {}

func (x *SpotDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotDetailsResponse.ProtoReflect.Descriptor instead.
func (*SpotDetailsResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{8}
}

func (x *SpotDetailsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpotDetailsResponse) GetSpotCode() string {
	if x != nil {
		return x.SpotCode
	}
	return ""
}

func (x *SpotDetailsResponse) GetFloorNumber() int32 {
	if x != nil {
		return x.FloorNumber
	}
	return 0
}

func (x *SpotDetailsResponse) GetSpotNumber() int32 {
	if x != nil {
		return x.SpotNumber
	}
	return 0
}

func (x *SpotDetailsResponse) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *SpotDetailsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_search_v1_search_proto protoreflect.FileDescriptor

const file_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x16search/v1/search.proto\x12\tsearch.v1\";\n" +
	"\x16GetAvailabilityRequest\x12!\n" +
	"\fvehicle_type\x18\x01 \x01(\tR\vvehicleType\"\x82\x01\n" +
	"\x14AvailabilityResponse\x124\n" +
	"\x06floors\x18\x01 \x03(\v2\x1c.search.v1.FloorAvailabilityR\x06floors\x124\n" +
	"\x05total\x18\x02 \x01(\v2\x1e.search.v1.AvailabilitySummaryR\x05total\"\xbe\x01\n" +
	"\x11FloorAvailability\x12!\n" +
	"\ffloor_number\x18\x01 \x01(\x05R\vfloorNumber\x12#\n" +
	"\ravailable_car\x18\x02 \x01(\x05R\favailableCar\x12%\n" +
	"\x0eavailable_moto\x18\x03 \x01(\x05R\ravailableMoto\x12\x1b\n" +
	"\ttotal_car\x18\x04 \x01(\x05R\btotalCar\x12\x1d\n" +
	"\n" +
	"total_moto\x18\x05 \x01(\x05R\ttotalMoto\"e\n" +
	"\x13AvailabilitySummary\x12'\n" +
	"\x0ftotal_available\x18\x01 \x01(\x05R\x0etotalAvailable\x12%\n" +
	"\x0etotal_capacity\x18\x02 \x01(\x05R\rtotalCapacity\"7\n" +
	"\x12GetFloorMapRequest\x12!\n" +
	"\ffloor_number\x18\x01 \x01(\x05R\vfloorNumber\"=\n" +
	"\x10FloorMapResponse\x12)\n" +
	"\x05spots\x18\x01 \x03(\v2\x13.search.v1.SpotInfoR\x05spots\"\xb6\x01\n" +
	"\bSpotInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tspot_code\x18\x02 \x01(\tR\bspotCode\x12!\n" +
	"\fvehicle_type\x18\x03 \x01(\tR\vvehicleType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\ffloor_number\x18\x05 \x01(\x05R\vfloorNumber\x12\x1f\n" +
	"\vspot_number\x18\x06 \x01(\x05R\n" +
	"spotNumber\"0\n" +
	"\x15GetSpotDetailsRequest\x12\x17\n" +
	"\aspot_id\x18\x01 \x01(\tR\x06spotId\"\xc1\x01\n" +
	"\x13SpotDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tspot_code\x18\x02 \x01(\tR\bspotCode\x12!\n" +
	"\ffloor_number\x18\x03 \x01(\x05R\vfloorNumber\x12\x1f\n" +
	"\vspot_number\x18\x04 \x01(\x05R\n" +
	"spotNumber\x12!\n" +
	"\fvehicle_type\x18\x05 \x01(\tR\vvehicleType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status2\x85\x02\n" +
	"\rSearchService\x12U\n" +
	"\x0fGetAvailability\x12!.search.v1.GetAvailabilityRequest\x1a\x1f.search.v1.AvailabilityResponse\x12I\n" +
	"\vGetFloorMap\x12\x1d.search.v1.GetFloorMapRequest\x1a\x1b.search.v1.FloorMapResponse\x12R\n" +
	"\x0eGetSpotDetails\x12 .search.v1.GetSpotDetailsRequest\x1a\x1e.search.v1.SpotDetailsResponseB(Z&parkir-pintar/proto/search/v1;searchv1b\x06proto3"

var (
	file_search_v1_search_proto_rawDescOnce sync.Once
	file_search_v1_search_proto_rawDescData []byte
)

func file_search_v1_search_proto_rawDescGZIP() []byte {
	file_search_v1_search_proto_rawDescOnce.Do(func() {
		file_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)))
	})
	return file_search_v1_search_proto_rawDescData
}

var file_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_search_v1_search_proto_goTypes = []any{
	(*GetAvailabilityRequest)(nil), // 0: search.v1.GetAvailabilityRequest
	(*AvailabilityResponse)(nil),   // 1: search.v1.AvailabilityResponse
	(*FloorAvailability)(nil),      // 2: search.v1.FloorAvailability
	(*AvailabilitySummary)(nil),    // 3: search.v1.AvailabilitySummary
	(*GetFloorMapRequest)(nil),     // 4: search.v1.GetFloorMapRequest
	(*FloorMapResponse)(nil),       // 5: search.v1.FloorMapResponse
	(*SpotInfo)(nil),               // 6: search.v1.SpotInfo
	(*GetSpotDetailsRequest)(nil),  // 7: search.v1.GetSpotDetailsRequest
	(*SpotDetailsResponse)(nil),    // 8: search.v1.SpotDetailsResponse
}
var file_search_v1_search_proto_depIdxs = []int32{
	2, // 0: search.v1.AvailabilityResponse.floors:type_name -> search.v1.FloorAvailability
	3, // 1: search.v1.AvailabilityResponse.total:type_name -> search.v1.AvailabilitySummary
	6, // 2: search.v1.FloorMapResponse.spots:type_name -> search.v1.SpotInfo
	0, // 3: search.v1.SearchService.GetAvailability:input_type -> search.v1.GetAvailabilityRequest
	4, // 4: search.v1.SearchService.GetFloorMap:input_type -> search.v1.GetFloorMapRequest
	7, // 5: search.v1.SearchService.GetSpotDetails:input_type -> search.v1.GetSpotDetailsRequest
	1, // 6: search.v1.SearchService.GetAvailability:output_type -> search.v1.AvailabilityResponse
	5, // 7: search.v1.SearchService.GetFloorMap:output_type -> search.v1.FloorMapResponse
	8, // 8: search.v1.SearchService.GetSpotDetails:output_type -> search.v1.SpotDetailsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_search_v1_search_proto_init() }
func file_search_v1_search_proto_init() {
	if File_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_v1_search_proto_goTypes,
		DependencyIndexes: file_search_v1_search_proto_depIdxs,
		MessageInfos:      file_search_v1_search_proto_msgTypes,
	}.Build()
	File_search_v1_search_proto = out.File
	file_search_v1_search_proto_goTypes = nil
	file_search_v1_search_proto_depIdxs = nil
}
