// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/presence/repository (interfaces: SensorGateway)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_sensor_gateway.go -package=mocks parkir-pintar/internal/presence/repository SensorGateway
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	repository "parkir-pintar/internal/presence/repository"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSensorGateway is a mock of SensorGateway interface.
type MockSensorGateway struct {
	ctrl     *gomock.Controller
	recorder *MockSensorGatewayMockRecorder
	isgomock struct{}
}

// MockSensorGatewayMockRecorder is the mock recorder for MockSensorGateway.
type MockSensorGatewayMockRecorder struct {
	mock *MockSensorGateway
}

// NewMockSensorGateway creates a new mock instance.
func NewMockSensorGateway(ctrl *gomock.Controller) *MockSensorGateway {
	mock := &MockSensorGateway{ctrl: ctrl}
	mock.recorder = &MockSensorGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSensorGateway) EXPECT() *MockSensorGatewayMockRecorder {
	return m.recorder
}

// CheckSpotOccupancy mocks base method.
func (m *MockSensorGateway) CheckSpotOccupancy(ctx context.Context, floorNumber, spotNumber int) (*repository.SensorReading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSpotOccupancy", ctx, floorNumber, spotNumber)
	ret0, _ := ret[0].(*repository.SensorReading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSpotOccupancy indicates an expected call of CheckSpotOccupancy.
func (mr *MockSensorGatewayMockRecorder) CheckSpotOccupancy(ctx, floorNumber, spotNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSpotOccupancy", reflect.TypeOf((*MockSensorGateway)(nil).CheckSpotOccupancy), ctx, floorNumber, spotNumber)
}
