// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/presence/usecase (interfaces: Usecase)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_usecase.go -package=mocks parkir-pintar/internal/presence/usecase Usecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	usecase "parkir-pintar/internal/presence/usecase"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// VerifyPresence mocks base method.
func (m *MockUsecase) VerifyPresence(ctx context.Context, reservationID string, floorNumber, spotNumber int) (*usecase.VerifyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPresence", ctx, reservationID, floorNumber, spotNumber)
	ret0, _ := ret[0].(*usecase.VerifyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyPresence indicates an expected call of VerifyPresence.
func (mr *MockUsecaseMockRecorder) VerifyPresence(ctx, reservationID, floorNumber, spotNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPresence", reflect.TypeOf((*MockUsecase)(nil).VerifyPresence), ctx, reservationID, floorNumber, spotNumber)
}
