// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: analytics/v1/analytics.proto

package analyticsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetPeakHours_FullMethodName     = "/analytics.v1.AnalyticsService/GetPeakHours"
	AnalyticsService_GetUsagePatterns_FullMethodName = "/analytics.v1.AnalyticsService/GetUsagePatterns"
	AnalyticsService_PredictResources_FullMethodName = "/analytics.v1.AnalyticsService/PredictResources"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AnalyticsService provides parking analytics and reporting.
type AnalyticsServiceClient interface {
	// GetPeakHours returns peak hour statistics from historical reservation data.
	GetPeakHours(ctx context.Context, in *GetPeakHoursRequest, opts ...grpc.CallOption) (*GetPeakHoursResponse, error)
	// GetUsagePatterns returns daily occupancy/usage patterns summarized over the last 30 days.
	GetUsagePatterns(ctx context.Context, in *GetUsagePatternsRequest, opts ...grpc.CallOption) (*GetUsagePatternsResponse, error)
	// PredictResources returns predicted occupancy and recommended resource allocation.
	PredictResources(ctx context.Context, in *PredictResourcesRequest, opts ...grpc.CallOption) (*PredictResourcesResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetPeakHours(ctx context.Context, in *GetPeakHoursRequest, opts ...grpc.CallOption) (*GetPeakHoursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeakHoursResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetPeakHours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetUsagePatterns(ctx context.Context, in *GetUsagePatternsRequest, opts ...grpc.CallOption) (*GetUsagePatternsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsagePatternsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetUsagePatterns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) PredictResources(ctx context.Context, in *PredictResourcesRequest, opts ...grpc.CallOption) (*PredictResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResourcesResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_PredictResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
//
// AnalyticsService provides parking analytics and reporting.
type AnalyticsServiceServer interface {
	// GetPeakHours returns peak hour statistics from historical reservation data.
	GetPeakHours(context.Context, *GetPeakHoursRequest) (*GetPeakHoursResponse, error)
	// GetUsagePatterns returns daily occupancy/usage patterns summarized over the last 30 days.
	GetUsagePatterns(context.Context, *GetUsagePatternsRequest) (*GetUsagePatternsResponse, error)
	// PredictResources returns predicted occupancy and recommended resource allocation.
	PredictResources(context.Context, *PredictResourcesRequest) (*PredictResourcesResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetPeakHours(context.Context, *GetPeakHoursRequest) (*GetPeakHoursResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPeakHours not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetUsagePatterns(context.Context, *GetUsagePatternsRequest) (*GetUsagePatternsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsagePatterns not implemented")
}
func (UnimplementedAnalyticsServiceServer) PredictResources(context.Context, *PredictResourcesRequest) (*PredictResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PredictResources not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetPeakHours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeakHoursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetPeakHours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetPeakHours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetPeakHours(ctx, req.(*GetPeakHoursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetUsagePatterns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsagePatternsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetUsagePatterns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetUsagePatterns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetUsagePatterns(ctx, req.(*GetUsagePatternsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_PredictResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).PredictResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_PredictResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).PredictResources(ctx, req.(*PredictResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPeakHours",
			Handler:    _AnalyticsService_GetPeakHours_Handler,
		},
		{
			MethodName: "GetUsagePatterns",
			Handler:    _AnalyticsService_GetUsagePatterns_Handler,
		},
		{
			MethodName: "PredictResources",
			Handler:    _AnalyticsService_PredictResources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics/v1/analytics.proto",
}
