// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: analytics/v1/analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPeakHoursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeakHoursRequest) Reset() {
	*x = GetPeakHoursRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeakHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeakHoursRequest) ProtoMessage() {}

func (x *GetPeakHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeakHoursRequest.ProtoReflect.Descriptor instead.
func (*GetPeakHoursRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

type GetPeakHoursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*PeakHourStats       `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeakHoursResponse) Reset() {
	*x = GetPeakHoursResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeakHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeakHoursResponse) ProtoMessage() {}

func (x *GetPeakHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeakHoursResponse.ProtoReflect.Descriptor instead.
func (*GetPeakHoursResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetPeakHoursResponse) GetStats() []*PeakHourStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type PeakHourStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hour            int32                  `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	DayOfWeek       int32                  `protobuf:"varint,2,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	AvgOccupancy    float64                `protobuf:"fixed64,3,opt,name=avg_occupancy,json=avgOccupancy,proto3" json:"avg_occupancy,omitempty"`
	AvgReservations int32                  `protobuf:"varint,4,opt,name=avg_reservations,json=avgReservations,proto3" json:"avg_reservations,omitempty"`
	PeakScore       float64                `protobuf:"fixed64,5,opt,name=peak_score,json=peakScore,proto3" json:"peak_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PeakHourStats) Reset() {
	*x = PeakHourStats{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeakHourStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeakHourStats) ProtoMessage() {}

func (x *PeakHourStats) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeakHourStats.ProtoReflect.Descriptor instead.
func (*PeakHourStats) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *PeakHourStats) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *PeakHourStats) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *PeakHourStats) GetAvgOccupancy() float64 {
	if x != nil {
		return x.AvgOccupancy
	}
	return 0
}

func (x *PeakHourStats) GetAvgReservations() int32 {
	if x != nil {
		return x.AvgReservations
	}
	return 0
}

func (x *PeakHourStats) GetPeakScore() float64 {
	if x != nil {
		return x.PeakScore
	}
	return 0
}

type GetUsagePatternsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsagePatternsRequest) Reset() {
	*x = GetUsagePatternsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsagePatternsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsagePatternsRequest) ProtoMessage() {}

func (x *GetUsagePatternsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsagePatternsRequest.ProtoReflect.Descriptor instead.
func (*GetUsagePatternsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{3}
}

type GetUsagePatternsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Period         string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	AvgUtilization float64                `protobuf:"fixed64,2,opt,name=avg_utilization,json=avgUtilization,proto3" json:"avg_utilization,omitempty"`
	PeakHours      []int32                `protobuf:"varint,3,rep,packed,name=peak_hours,json=peakHours,proto3" json:"peak_hours,omitempty"`
	IdleHours      []int32                `protobuf:"varint,4,rep,packed,name=idle_hours,json=idleHours,proto3" json:"idle_hours,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUsagePatternsResponse) Reset() {
	*x = GetUsagePatternsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsagePatternsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsagePatternsResponse) ProtoMessage() {}

func (x *GetUsagePatternsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsagePatternsResponse.ProtoReflect.Descriptor instead.
func (*GetUsagePatternsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetUsagePatternsResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetUsagePatternsResponse) GetAvgUtilization() float64 {
	if x != nil {
		return x.AvgUtilization
	}
	return 0
}

func (x *GetUsagePatternsResponse) GetPeakHours() []int32 {
	if x != nil {
		return x.PeakHours
	}
	return nil
}

func (x *GetUsagePatternsResponse) GetIdleHours() []int32 {
	if x != nil {
		return x.IdleHours
	}
	return nil
}

var File_analytics_v1_analytics_proto protoreflect.FileDescriptor

const file_analytics_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1canalytics/v1/analytics.proto\x12\fanalytics.v1\"\x15\n" +
	"\x13GetPeakHoursRequest\"I\n" +
	"\x14GetPeakHoursResponse\x121\n" +
	"\x05stats\x18\x01 \x03(\v2\x1b.analytics.v1.PeakHourStatsR\x05stats\"\xb2\x01\n" +
	"\rPeakHourStats\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\x05R\x04hour\x12\x1e\n" +
	"\vday_of_week\x18\x02 \x01(\x05R\tdayOfWeek\x12#\n" +
	"\ravg_occupancy\x18\x03 \x01(\x01R\favgOccupancy\x12)\n" +
	"\x10avg_reservations\x18\x04 \x01(\x05R\x0favgReservations\x12\x1d\n" +
	"\n" +
	"peak_score\x18\x05 \x01(\x01R\tpeakScore\"\x19\n" +
	"\x17GetUsagePatternsRequest\"\x99\x01\n" +
	"\x18GetUsagePatternsResponse\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12'\n" +
	"\x0favg_utilization\x18\x02 \x01(\x01R\x0eavgUtilization\x12\x1d\n" +
	"\n" +
	"peak_hours\x18\x03 \x03(\x05R\tpeakHours\x12\x1d\n" +
	"\n" +
	"idle_hours\x18\x04 \x03(\x05R\tidleHours2\xcc\x01\n" +
	"\x10AnalyticsService\x12U\n" +
	"\fGetPeakHours\x12!.analytics.v1.GetPeakHoursRequest\x1a\".analytics.v1.GetPeakHoursResponse\x12a\n" +
	"\x10GetUsagePatterns\x12%.analytics.v1.GetUsagePatternsRequest\x1a&.analytics.v1.GetUsagePatternsResponseB.Z,parkir-pintar/proto/analytics/v1;analyticsv1b\x06proto3"

var (
	file_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_analytics_v1_analytics_proto_rawDescData []byte
)

func file_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)))
	})
	return file_analytics_v1_analytics_proto_rawDescData
}

var file_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_analytics_v1_analytics_proto_goTypes = []any{
	(*GetPeakHoursRequest)(nil),      // 0: analytics.v1.GetPeakHoursRequest
	(*GetPeakHoursResponse)(nil),     // 1: analytics.v1.GetPeakHoursResponse
	(*PeakHourStats)(nil),            // 2: analytics.v1.PeakHourStats
	(*GetUsagePatternsRequest)(nil),  // 3: analytics.v1.GetUsagePatternsRequest
	(*GetUsagePatternsResponse)(nil), // 4: analytics.v1.GetUsagePatternsResponse
}
var file_analytics_v1_analytics_proto_depIdxs = []int32{
	2, // 0: analytics.v1.GetPeakHoursResponse.stats:type_name -> analytics.v1.PeakHourStats
	0, // 1: analytics.v1.AnalyticsService.GetPeakHours:input_type -> analytics.v1.GetPeakHoursRequest
	3, // 2: analytics.v1.AnalyticsService.GetUsagePatterns:input_type -> analytics.v1.GetUsagePatternsRequest
	1, // 3: analytics.v1.AnalyticsService.GetPeakHours:output_type -> analytics.v1.GetPeakHoursResponse
	4, // 4: analytics.v1.AnalyticsService.GetUsagePatterns:output_type -> analytics.v1.GetUsagePatternsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_analytics_v1_analytics_proto_init() }
func file_analytics_v1_analytics_proto_init() {
	if File_analytics_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_v1_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_analytics_v1_analytics_proto = out.File
	file_analytics_v1_analytics_proto_goTypes = nil
	file_analytics_v1_analytics_proto_depIdxs = nil
}
