// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/reservation (interfaces: BillingClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_billing_client.go -package=mocks parkir-pintar/internal/reservation BillingClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reservation "parkir-pintar/internal/reservation"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockBillingClient is a mock of BillingClient interface.
type MockBillingClient struct {
	ctrl     *gomock.Controller
	recorder *MockBillingClientMockRecorder
	isgomock struct{}
}

// MockBillingClientMockRecorder is the mock recorder for MockBillingClient.
type MockBillingClientMockRecorder struct {
	mock *MockBillingClient
}

// NewMockBillingClient creates a new mock instance.
func NewMockBillingClient(ctrl *gomock.Controller) *MockBillingClient {
	mock := &MockBillingClient{ctrl: ctrl}
	mock.recorder = &MockBillingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingClient) EXPECT() *MockBillingClientMockRecorder {
	return m.recorder
}

// CalculateFee mocks base method.
func (m *MockBillingClient) CalculateFee(ctx context.Context, reservationID string, checkInAt, checkOutAt time.Time) (*reservation.BillingRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateFee", ctx, reservationID, checkInAt, checkOutAt)
	ret0, _ := ret[0].(*reservation.BillingRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateFee indicates an expected call of CalculateFee.
func (mr *MockBillingClientMockRecorder) CalculateFee(ctx, reservationID, checkInAt, checkOutAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateFee", reflect.TypeOf((*MockBillingClient)(nil).CalculateFee), ctx, reservationID, checkInAt, checkOutAt)
}

// GenerateInvoice mocks base method.
func (m *MockBillingClient) GenerateInvoice(ctx context.Context, reservationID, idempotencyKey string) (*reservation.BillingRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateInvoice", ctx, reservationID, idempotencyKey)
	ret0, _ := ret[0].(*reservation.BillingRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateInvoice indicates an expected call of GenerateInvoice.
func (mr *MockBillingClientMockRecorder) GenerateInvoice(ctx, reservationID, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateInvoice", reflect.TypeOf((*MockBillingClient)(nil).GenerateInvoice), ctx, reservationID, idempotencyKey)
}

// StartBilling mocks base method.
func (m *MockBillingClient) StartBilling(ctx context.Context, reservationID string, bookingFee int64, idempotencyKey string) (*reservation.BillingRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartBilling", ctx, reservationID, bookingFee, idempotencyKey)
	ret0, _ := ret[0].(*reservation.BillingRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartBilling indicates an expected call of StartBilling.
func (mr *MockBillingClientMockRecorder) StartBilling(ctx, reservationID, bookingFee, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartBilling", reflect.TypeOf((*MockBillingClient)(nil).StartBilling), ctx, reservationID, bookingFee, idempotencyKey)
}
