// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/reservation (interfaces: PresenceClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/reservation/mocks/mock_presence_client.go -package=mocks parkir-pintar/internal/reservation PresenceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reservation "parkir-pintar/internal/reservation"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPresenceClient is a mock of PresenceClient interface.
type MockPresenceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPresenceClientMockRecorder
	isgomock struct{}
}

// MockPresenceClientMockRecorder is the mock recorder for MockPresenceClient.
type MockPresenceClientMockRecorder struct {
	mock *MockPresenceClient
}

// NewMockPresenceClient creates a new mock instance.
func NewMockPresenceClient(ctrl *gomock.Controller) *MockPresenceClient {
	mock := &MockPresenceClient{ctrl: ctrl}
	mock.recorder = &MockPresenceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPresenceClient) EXPECT() *MockPresenceClientMockRecorder {
	return m.recorder
}

// VerifyPresence mocks base method.
func (m *MockPresenceClient) VerifyPresence(ctx context.Context, driverID, reservationID string, floorNumber, spotNumber int) (*reservation.PresenceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPresence", ctx, driverID, reservationID, floorNumber, spotNumber)
	ret0, _ := ret[0].(*reservation.PresenceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyPresence indicates an expected call of VerifyPresence.
func (mr *MockPresenceClientMockRecorder) VerifyPresence(ctx, driverID, reservationID, floorNumber, spotNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPresence", reflect.TypeOf((*MockPresenceClient)(nil).VerifyPresence), ctx, driverID, reservationID, floorNumber, spotNumber)
}
