// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/reservation/gateway (interfaces: EventPublisher)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_event_publisher.go -package=mocks parkir-pintar/internal/reservation/gateway EventPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gateway "parkir-pintar/internal/reservation/gateway"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishReservationEvent mocks base method.
func (m *MockEventPublisher) PublishReservationEvent(ctx context.Context, subject string, event gateway.ReservationEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishReservationEvent", ctx, subject, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishReservationEvent indicates an expected call of PublishReservationEvent.
func (mr *MockEventPublisherMockRecorder) PublishReservationEvent(ctx, subject, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishReservationEvent", reflect.TypeOf((*MockEventPublisher)(nil).PublishReservationEvent), ctx, subject, event)
}

// PublishSpotUpdated mocks base method.
func (m *MockEventPublisher) PublishSpotUpdated(ctx context.Context, event gateway.SpotUpdatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSpotUpdated", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSpotUpdated indicates an expected call of PublishSpotUpdated.
func (mr *MockEventPublisherMockRecorder) PublishSpotUpdated(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSpotUpdated", reflect.TypeOf((*MockEventPublisher)(nil).PublishSpotUpdated), ctx, event)
}
