// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/reservation (interfaces: TaskEnqueuer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_task_enqueuer.go -package=mocks parkir-pintar/internal/reservation TaskEnqueuer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskEnqueuer is a mock of TaskEnqueuer interface.
type MockTaskEnqueuer struct {
	ctrl     *gomock.Controller
	recorder *MockTaskEnqueuerMockRecorder
	isgomock struct{}
}

// MockTaskEnqueuerMockRecorder is the mock recorder for MockTaskEnqueuer.
type MockTaskEnqueuerMockRecorder struct {
	mock *MockTaskEnqueuer
}

// NewMockTaskEnqueuer creates a new mock instance.
func NewMockTaskEnqueuer(ctrl *gomock.Controller) *MockTaskEnqueuer {
	mock := &MockTaskEnqueuer{ctrl: ctrl}
	mock.recorder = &MockTaskEnqueuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskEnqueuer) EXPECT() *MockTaskEnqueuerMockRecorder {
	return m.recorder
}

// CancelTask mocks base method.
func (m *MockTaskEnqueuer) CancelTask(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelTask indicates an expected call of CancelTask.
func (mr *MockTaskEnqueuerMockRecorder) CancelTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTask", reflect.TypeOf((*MockTaskEnqueuer)(nil).CancelTask), ctx, taskID)
}

// EnqueuePaymentHoldTimeout mocks base method.
func (m *MockTaskEnqueuer) EnqueuePaymentHoldTimeout(ctx context.Context, reservationID, paymentID string, delay time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueuePaymentHoldTimeout", ctx, reservationID, paymentID, delay)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnqueuePaymentHoldTimeout indicates an expected call of EnqueuePaymentHoldTimeout.
func (mr *MockTaskEnqueuerMockRecorder) EnqueuePaymentHoldTimeout(ctx, reservationID, paymentID, delay any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueuePaymentHoldTimeout", reflect.TypeOf((*MockTaskEnqueuer)(nil).EnqueuePaymentHoldTimeout), ctx, reservationID, paymentID, delay)
}

// EnqueueReservationExpiry mocks base method.
func (m *MockTaskEnqueuer) EnqueueReservationExpiry(ctx context.Context, reservationID string, delay time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueReservationExpiry", ctx, reservationID, delay)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnqueueReservationExpiry indicates an expected call of EnqueueReservationExpiry.
func (mr *MockTaskEnqueuerMockRecorder) EnqueueReservationExpiry(ctx, reservationID, delay any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueReservationExpiry", reflect.TypeOf((*MockTaskEnqueuer)(nil).EnqueueReservationExpiry), ctx, reservationID, delay)
}
