// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/reservation (interfaces: PaymentClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/reservation/mocks/mock_payment_client.go -package=mocks parkir-pintar/internal/reservation PaymentClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPaymentClient is a mock of PaymentClient interface.
type MockPaymentClient struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentClientMockRecorder
	isgomock struct{}
}

// MockPaymentClientMockRecorder is the mock recorder for MockPaymentClient.
type MockPaymentClientMockRecorder struct {
	mock *MockPaymentClient
}

// NewMockPaymentClient creates a new mock instance.
func NewMockPaymentClient(ctrl *gomock.Controller) *MockPaymentClient {
	mock := &MockPaymentClient{ctrl: ctrl}
	mock.recorder = &MockPaymentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentClient) EXPECT() *MockPaymentClientMockRecorder {
	return m.recorder
}

// ProcessPayment mocks base method.
func (m *MockPaymentClient) ProcessPayment(ctx context.Context, billingID string, amount int64, paymentMethod, idempotencyKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPayment", ctx, billingID, amount, paymentMethod, idempotencyKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessPayment indicates an expected call of ProcessPayment.
func (mr *MockPaymentClientMockRecorder) ProcessPayment(ctx, billingID, amount, paymentMethod, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPayment", reflect.TypeOf((*MockPaymentClient)(nil).ProcessPayment), ctx, billingID, amount, paymentMethod, idempotencyKey)
}

// RefundPayment mocks base method.
func (m *MockPaymentClient) RefundPayment(ctx context.Context, paymentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefundPayment", ctx, paymentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefundPayment indicates an expected call of RefundPayment.
func (mr *MockPaymentClientMockRecorder) RefundPayment(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefundPayment", reflect.TypeOf((*MockPaymentClient)(nil).RefundPayment), ctx, paymentID)
}
