// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/reservation (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/reservation/mocks/mock_repository.go -package=mocks parkir-pintar/internal/reservation Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "parkir-pintar/internal/reservation/model"
	reflect "reflect"

	sqlx "github.com/jmoiron/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateReservationTx mocks base method.
func (m *MockRepository) CreateReservationTx(ctx context.Context, tx *sqlx.Tx, reservation *model.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReservationTx", ctx, tx, reservation)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReservationTx indicates an expected call of CreateReservationTx.
func (mr *MockRepositoryMockRecorder) CreateReservationTx(ctx, tx, reservation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReservationTx", reflect.TypeOf((*MockRepository)(nil).CreateReservationTx), ctx, tx, reservation)
}

// FindAvailableSpot mocks base method.
func (m *MockRepository) FindAvailableSpot(ctx context.Context, vehicleType string) (*model.ParkingSpot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailableSpot", ctx, vehicleType)
	ret0, _ := ret[0].(*model.ParkingSpot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailableSpot indicates an expected call of FindAvailableSpot.
func (mr *MockRepositoryMockRecorder) FindAvailableSpot(ctx, vehicleType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailableSpot", reflect.TypeOf((*MockRepository)(nil).FindAvailableSpot), ctx, vehicleType)
}

// FindByIdempotencyKey mocks base method.
func (m *MockRepository) FindByIdempotencyKey(ctx context.Context, key string) (*model.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdempotencyKey indicates an expected call of FindByIdempotencyKey.
func (mr *MockRepositoryMockRecorder) FindByIdempotencyKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdempotencyKey", reflect.TypeOf((*MockRepository)(nil).FindByIdempotencyKey), ctx, key)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id string) (*model.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetByIDForUpdate mocks base method.
func (m *MockRepository) GetByIDForUpdate(ctx context.Context, tx *sqlx.Tx, id string) (*model.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDForUpdate", ctx, tx, id)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDForUpdate indicates an expected call of GetByIDForUpdate.
func (mr *MockRepositoryMockRecorder) GetByIDForUpdate(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDForUpdate", reflect.TypeOf((*MockRepository)(nil).GetByIDForUpdate), ctx, tx, id)
}

// GetSpotByID mocks base method.
func (m *MockRepository) GetSpotByID(ctx context.Context, spotID string) (*model.ParkingSpot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotByID", ctx, spotID)
	ret0, _ := ret[0].(*model.ParkingSpot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpotByID indicates an expected call of GetSpotByID.
func (mr *MockRepositoryMockRecorder) GetSpotByID(ctx, spotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotByID", reflect.TypeOf((*MockRepository)(nil).GetSpotByID), ctx, spotID)
}

// GetSpotForUpdateTx mocks base method.
func (m *MockRepository) GetSpotForUpdateTx(ctx context.Context, tx *sqlx.Tx, spotID string) (*model.ParkingSpot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotForUpdateTx", ctx, tx, spotID)
	ret0, _ := ret[0].(*model.ParkingSpot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpotForUpdateTx indicates an expected call of GetSpotForUpdateTx.
func (mr *MockRepositoryMockRecorder) GetSpotForUpdateTx(ctx, tx, spotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotForUpdateTx", reflect.TypeOf((*MockRepository)(nil).GetSpotForUpdateTx), ctx, tx, spotID)
}

// ListByDriverID mocks base method.
func (m *MockRepository) ListByDriverID(ctx context.Context, driverID, status string) ([]*model.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDriverID", ctx, driverID, status)
	ret0, _ := ret[0].([]*model.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDriverID indicates an expected call of ListByDriverID.
func (mr *MockRepositoryMockRecorder) ListByDriverID(ctx, driverID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDriverID", reflect.TypeOf((*MockRepository)(nil).ListByDriverID), ctx, driverID, status)
}

// UpdateReservationTx mocks base method.
func (m *MockRepository) UpdateReservationTx(ctx context.Context, tx *sqlx.Tx, reservation *model.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReservationTx", ctx, tx, reservation)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReservationTx indicates an expected call of UpdateReservationTx.
func (mr *MockRepositoryMockRecorder) UpdateReservationTx(ctx, tx, reservation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReservationTx", reflect.TypeOf((*MockRepository)(nil).UpdateReservationTx), ctx, tx, reservation)
}

// UpdateSpotStatusTx mocks base method.
func (m *MockRepository) UpdateSpotStatusTx(ctx context.Context, tx *sqlx.Tx, spotID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSpotStatusTx", ctx, tx, spotID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSpotStatusTx indicates an expected call of UpdateSpotStatusTx.
func (mr *MockRepositoryMockRecorder) UpdateSpotStatusTx(ctx, tx, spotID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSpotStatusTx", reflect.TypeOf((*MockRepository)(nil).UpdateSpotStatusTx), ctx, tx, spotID, status)
}

// WithTransaction mocks base method.
func (m *MockRepository) WithTransaction(ctx context.Context, fn func(*sqlx.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockRepositoryMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockRepository)(nil).WithTransaction), ctx, fn)
}
