// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/reservation (interfaces: Usecase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_usecase.go -package=mocks parkir-pintar/internal/reservation Usecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "parkir-pintar/internal/reservation/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CancelReservation mocks base method.
func (m *MockUsecase) CancelReservation(ctx context.Context, req *model.CancelReservationRequest) (*model.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelReservation", ctx, req)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelReservation indicates an expected call of CancelReservation.
func (mr *MockUsecaseMockRecorder) CancelReservation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelReservation", reflect.TypeOf((*MockUsecase)(nil).CancelReservation), ctx, req)
}

// CheckIn mocks base method.
func (m *MockUsecase) CheckIn(ctx context.Context, req *model.CheckInRequest) (*model.CheckInResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIn", ctx, req)
	ret0, _ := ret[0].(*model.CheckInResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckIn indicates an expected call of CheckIn.
func (mr *MockUsecaseMockRecorder) CheckIn(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIn", reflect.TypeOf((*MockUsecase)(nil).CheckIn), ctx, req)
}

// CheckOut mocks base method.
func (m *MockUsecase) CheckOut(ctx context.Context, req *model.CheckOutRequest) (*model.CheckOutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOut", ctx, req)
	ret0, _ := ret[0].(*model.CheckOutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckOut indicates an expected call of CheckOut.
func (mr *MockUsecaseMockRecorder) CheckOut(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOut", reflect.TypeOf((*MockUsecase)(nil).CheckOut), ctx, req)
}

// CompleteCheckout mocks base method.
func (m *MockUsecase) CompleteCheckout(ctx context.Context, req *model.CompleteCheckoutRequest) (*model.CheckOutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteCheckout", ctx, req)
	ret0, _ := ret[0].(*model.CheckOutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteCheckout indicates an expected call of CompleteCheckout.
func (mr *MockUsecaseMockRecorder) CompleteCheckout(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteCheckout", reflect.TypeOf((*MockUsecase)(nil).CompleteCheckout), ctx, req)
}

// ConfirmReservation mocks base method.
func (m *MockUsecase) ConfirmReservation(ctx context.Context, req *model.ConfirmReservationRequest) (*model.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmReservation", ctx, req)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmReservation indicates an expected call of ConfirmReservation.
func (mr *MockUsecaseMockRecorder) ConfirmReservation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmReservation", reflect.TypeOf((*MockUsecase)(nil).ConfirmReservation), ctx, req)
}

// CreateReservation mocks base method.
func (m *MockUsecase) CreateReservation(ctx context.Context, req *model.CreateReservationRequest) (*model.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReservation", ctx, req)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReservation indicates an expected call of CreateReservation.
func (mr *MockUsecaseMockRecorder) CreateReservation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReservation", reflect.TypeOf((*MockUsecase)(nil).CreateReservation), ctx, req)
}

// ExpireReservation mocks base method.
func (m *MockUsecase) ExpireReservation(ctx context.Context, req *model.ExpireReservationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireReservation", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExpireReservation indicates an expected call of ExpireReservation.
func (mr *MockUsecaseMockRecorder) ExpireReservation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireReservation", reflect.TypeOf((*MockUsecase)(nil).ExpireReservation), ctx, req)
}

// FailReservation mocks base method.
func (m *MockUsecase) FailReservation(ctx context.Context, req *model.FailReservationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailReservation", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailReservation indicates an expected call of FailReservation.
func (mr *MockUsecaseMockRecorder) FailReservation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailReservation", reflect.TypeOf((*MockUsecase)(nil).FailReservation), ctx, req)
}

// GetReservation mocks base method.
func (m *MockUsecase) GetReservation(ctx context.Context, id, callerID string) (*model.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservation", ctx, id, callerID)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReservation indicates an expected call of GetReservation.
func (mr *MockUsecaseMockRecorder) GetReservation(ctx, id, callerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservation", reflect.TypeOf((*MockUsecase)(nil).GetReservation), ctx, id, callerID)
}

// ListByDriver mocks base method.
func (m *MockUsecase) ListByDriver(ctx context.Context, driverID, status string) ([]*model.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDriver", ctx, driverID, status)
	ret0, _ := ret[0].([]*model.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDriver indicates an expected call of ListByDriver.
func (mr *MockUsecaseMockRecorder) ListByDriver(ctx, driverID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDriver", reflect.TypeOf((*MockUsecase)(nil).ListByDriver), ctx, driverID, status)
}
