// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: billing/v1/billing.proto

package billingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingServiceClient interface {
	// StartBilling creates a billing record when a reservation is confirmed.
	StartBilling(ctx context.Context, in *StartBillingRequest, opts ...grpc.CallOption) (*BillingResponse, error)
	// CalculateFee computes the parking fee based on actual session duration.
	CalculateFee(ctx context.Context, in *CalculateFeeRequest, opts ...grpc.CallOption) (*BillingResponse, error)
	// GenerateInvoice generates an idempotent invoice for a reservation.
	GenerateInvoice(ctx context.Context, in *GenerateInvoiceRequest, opts ...grpc.CallOption) (*BillingResponse, error)
	// ApplyPenalty applies a penalty (wrong-spot, no-show) to a billing record.
	ApplyPenalty(ctx context.Context, in *ApplyPenaltyRequest, opts ...grpc.CallOption) (*BillingResponse, error)
	// ApplyOvernightFee applies the overnight flat fee to a billing record.
	ApplyOvernightFee(ctx context.Context, in *ApplyOvernightFeeRequest, opts ...grpc.CallOption) (*BillingResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) StartBilling(ctx context.Context, in *StartBillingRequest, opts ...grpc.CallOption) (*BillingResponse, error) {
	out := new(BillingResponse)
	err := c.cc.Invoke(ctx, "/billing.v1.BillingService/StartBilling", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CalculateFee(ctx context.Context, in *CalculateFeeRequest, opts ...grpc.CallOption) (*BillingResponse, error) {
	out := new(BillingResponse)
	err := c.cc.Invoke(ctx, "/billing.v1.BillingService/CalculateFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GenerateInvoice(ctx context.Context, in *GenerateInvoiceRequest, opts ...grpc.CallOption) (*BillingResponse, error) {
	out := new(BillingResponse)
	err := c.cc.Invoke(ctx, "/billing.v1.BillingService/GenerateInvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ApplyPenalty(ctx context.Context, in *ApplyPenaltyRequest, opts ...grpc.CallOption) (*BillingResponse, error) {
	out := new(BillingResponse)
	err := c.cc.Invoke(ctx, "/billing.v1.BillingService/ApplyPenalty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) ApplyOvernightFee(ctx context.Context, in *ApplyOvernightFeeRequest, opts ...grpc.CallOption) (*BillingResponse, error) {
	out := new(BillingResponse)
	err := c.cc.Invoke(ctx, "/billing.v1.BillingService/ApplyOvernightFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility
type BillingServiceServer interface {
	// StartBilling creates a billing record when a reservation is confirmed.
	StartBilling(context.Context, *StartBillingRequest) (*BillingResponse, error)
	// CalculateFee computes the parking fee based on actual session duration.
	CalculateFee(context.Context, *CalculateFeeRequest) (*BillingResponse, error)
	// GenerateInvoice generates an idempotent invoice for a reservation.
	GenerateInvoice(context.Context, *GenerateInvoiceRequest) (*BillingResponse, error)
	// ApplyPenalty applies a penalty (wrong-spot, no-show) to a billing record.
	ApplyPenalty(context.Context, *ApplyPenaltyRequest) (*BillingResponse, error)
	// ApplyOvernightFee applies the overnight flat fee to a billing record.
	ApplyOvernightFee(context.Context, *ApplyOvernightFeeRequest) (*BillingResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBillingServiceServer struct {
}

func (UnimplementedBillingServiceServer) StartBilling(context.Context, *StartBillingRequest) (*BillingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartBilling not implemented")
}
func (UnimplementedBillingServiceServer) CalculateFee(context.Context, *CalculateFeeRequest) (*BillingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateFee not implemented")
}
func (UnimplementedBillingServiceServer) GenerateInvoice(context.Context, *GenerateInvoiceRequest) (*BillingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateInvoice not implemented")
}
func (UnimplementedBillingServiceServer) ApplyPenalty(context.Context, *ApplyPenaltyRequest) (*BillingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyPenalty not implemented")
}
func (UnimplementedBillingServiceServer) ApplyOvernightFee(context.Context, *ApplyOvernightFeeRequest) (*BillingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyOvernightFee not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_StartBilling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBillingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).StartBilling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.v1.BillingService/StartBilling",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).StartBilling(ctx, req.(*StartBillingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CalculateFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CalculateFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.v1.BillingService/CalculateFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CalculateFee(ctx, req.(*CalculateFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GenerateInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GenerateInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.v1.BillingService/GenerateInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GenerateInvoice(ctx, req.(*GenerateInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ApplyPenalty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPenaltyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ApplyPenalty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.v1.BillingService/ApplyPenalty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ApplyPenalty(ctx, req.(*ApplyPenaltyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_ApplyOvernightFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyOvernightFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).ApplyOvernightFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/billing.v1.BillingService/ApplyOvernightFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).ApplyOvernightFee(ctx, req.(*ApplyOvernightFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.v1.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartBilling",
			Handler:    _BillingService_StartBilling_Handler,
		},
		{
			MethodName: "CalculateFee",
			Handler:    _BillingService_CalculateFee_Handler,
		},
		{
			MethodName: "GenerateInvoice",
			Handler:    _BillingService_GenerateInvoice_Handler,
		},
		{
			MethodName: "ApplyPenalty",
			Handler:    _BillingService_ApplyPenalty_Handler,
		},
		{
			MethodName: "ApplyOvernightFee",
			Handler:    _BillingService_ApplyOvernightFee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing/v1/billing.proto",
}
