// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: proto/billing/v1/billing.proto

package billingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartBillingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReservationId  string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	BookingFee     int64                  `protobuf:"varint,2,opt,name=booking_fee,json=bookingFee,proto3" json:"booking_fee,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartBillingRequest) Reset() {
	*x = StartBillingRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBillingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBillingRequest) ProtoMessage() {}

func (x *StartBillingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBillingRequest.ProtoReflect.Descriptor instead.
func (*StartBillingRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *StartBillingRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *StartBillingRequest) GetBookingFee() int64 {
	if x != nil {
		return x.BookingFee
	}
	return 0
}

func (x *StartBillingRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CalculateFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	CheckInAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=check_in_at,json=checkInAt,proto3" json:"check_in_at,omitempty"`
	CheckOutAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=check_out_at,json=checkOutAt,proto3" json:"check_out_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateFeeRequest) Reset() {
	*x = CalculateFeeRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateFeeRequest) ProtoMessage() {}

func (x *CalculateFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateFeeRequest.ProtoReflect.Descriptor instead.
func (*CalculateFeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateFeeRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CalculateFeeRequest) GetCheckInAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckInAt
	}
	return nil
}

func (x *CalculateFeeRequest) GetCheckOutAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckOutAt
	}
	return nil
}

type GenerateInvoiceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReservationId  string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateInvoiceRequest) Reset() {
	*x = GenerateInvoiceRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateInvoiceRequest) ProtoMessage() {}

func (x *GenerateInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GenerateInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateInvoiceRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *GenerateInvoiceRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ApplyOvernightFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyOvernightFeeRequest) Reset() {
	*x = ApplyOvernightFeeRequest{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyOvernightFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOvernightFeeRequest) ProtoMessage() {}

func (x *ApplyOvernightFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOvernightFeeRequest.ProtoReflect.Descriptor instead.
func (*ApplyOvernightFeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyOvernightFeeRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type BillingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReservationId   string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	BookingFee      int64                  `protobuf:"varint,3,opt,name=booking_fee,json=bookingFee,proto3" json:"booking_fee,omitempty"`
	ParkingFee      int64                  `protobuf:"varint,4,opt,name=parking_fee,json=parkingFee,proto3" json:"parking_fee,omitempty"`
	OvernightFee    int64                  `protobuf:"varint,5,opt,name=overnight_fee,json=overnightFee,proto3" json:"overnight_fee,omitempty"`
	TotalAmount     int64                  `protobuf:"varint,8,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,9,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	BilledHours     int32                  `protobuf:"varint,10,opt,name=billed_hours,json=billedHours,proto3" json:"billed_hours,omitempty"`
	IsOvernight     bool                   `protobuf:"varint,11,opt,name=is_overnight,json=isOvernight,proto3" json:"is_overnight,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,12,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Status          string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BillingResponse) Reset() {
	*x = BillingResponse{}
	mi := &file_proto_billing_v1_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingResponse) ProtoMessage() {}

func (x *BillingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_billing_v1_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingResponse.ProtoReflect.Descriptor instead.
func (*BillingResponse) Descriptor() ([]byte, []int) {
	return file_proto_billing_v1_billing_proto_rawDescGZIP(), []int{4}
}

func (x *BillingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BillingResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *BillingResponse) GetBookingFee() int64 {
	if x != nil {
		return x.BookingFee
	}
	return 0
}

func (x *BillingResponse) GetParkingFee() int64 {
	if x != nil {
		return x.ParkingFee
	}
	return 0
}

func (x *BillingResponse) GetOvernightFee() int64 {
	if x != nil {
		return x.OvernightFee
	}
	return 0
}

func (x *BillingResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *BillingResponse) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *BillingResponse) GetBilledHours() int32 {
	if x != nil {
		return x.BilledHours
	}
	return 0
}

func (x *BillingResponse) GetIsOvernight() bool {
	if x != nil {
		return x.IsOvernight
	}
	return false
}

func (x *BillingResponse) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *BillingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_billing_v1_billing_proto protoreflect.FileDescriptor

const file_proto_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/billing/v1/billing.proto\x12\n" +
	"billing.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x01\n" +
	"\x13StartBillingRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1f\n" +
	"\vbooking_fee\x18\x02 \x01(\x03R\n" +
	"bookingFee\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\xb6\x01\n" +
	"\x13CalculateFeeRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12:\n" +
	"\vcheck_in_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckInAt\x12<\n" +
	"\fcheck_out_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"checkOutAt\"h\n" +
	"\x16GenerateInvoiceRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"A\n" +
	"\x18ApplyOvernightFeeRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"\x84\x03\n" +
	"\x0fBillingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12\x1f\n" +
	"\vbooking_fee\x18\x03 \x01(\x03R\n" +
	"bookingFee\x12\x1f\n" +
	"\vparking_fee\x18\x04 \x01(\x03R\n" +
	"parkingFee\x12#\n" +
	"\rovernight_fee\x18\x05 \x01(\x03R\fovernightFee\x12!\n" +
	"\ftotal_amount\x18\b \x01(\x03R\vtotalAmount\x12)\n" +
	"\x10duration_minutes\x18\t \x01(\x05R\x0fdurationMinutes\x12!\n" +
	"\fbilled_hours\x18\n" +
	" \x01(\x05R\vbilledHours\x12!\n" +
	"\fis_overnight\x18\v \x01(\bR\visOvernight\x12'\n" +
	"\x0fidempotency_key\x18\f \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status2\xd8\x02\n" +
	"\x0eBillingService\x12L\n" +
	"\fStartBilling\x12\x1f.billing.v1.StartBillingRequest\x1a\x1b.billing.v1.BillingResponse\x12L\n" +
	"\fCalculateFee\x12\x1f.billing.v1.CalculateFeeRequest\x1a\x1b.billing.v1.BillingResponse\x12R\n" +
	"\x0fGenerateInvoice\x12\".billing.v1.GenerateInvoiceRequest\x1a\x1b.billing.v1.BillingResponse\x12V\n" +
	"\x11ApplyOvernightFee\x12$.billing.v1.ApplyOvernightFeeRequest\x1a\x1b.billing.v1.BillingResponseB*Z(parkir-pintar/proto/billing/v1;billingv1b\x06proto3"

var (
	file_proto_billing_v1_billing_proto_rawDescOnce sync.Once
	file_proto_billing_v1_billing_proto_rawDescData []byte
)

func file_proto_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_proto_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_proto_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_billing_v1_billing_proto_rawDesc), len(file_proto_billing_v1_billing_proto_rawDesc)))
	})
	return file_proto_billing_v1_billing_proto_rawDescData
}

var file_proto_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_billing_v1_billing_proto_goTypes = []any{
	(*StartBillingRequest)(nil),      // 0: billing.v1.StartBillingRequest
	(*CalculateFeeRequest)(nil),      // 1: billing.v1.CalculateFeeRequest
	(*GenerateInvoiceRequest)(nil),   // 2: billing.v1.GenerateInvoiceRequest
	(*ApplyOvernightFeeRequest)(nil), // 3: billing.v1.ApplyOvernightFeeRequest
	(*BillingResponse)(nil),          // 4: billing.v1.BillingResponse
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
}
var file_proto_billing_v1_billing_proto_depIdxs = []int32{
	5, // 0: billing.v1.CalculateFeeRequest.check_in_at:type_name -> google.protobuf.Timestamp
	5, // 1: billing.v1.CalculateFeeRequest.check_out_at:type_name -> google.protobuf.Timestamp
	0, // 2: billing.v1.BillingService.StartBilling:input_type -> billing.v1.StartBillingRequest
	1, // 3: billing.v1.BillingService.CalculateFee:input_type -> billing.v1.CalculateFeeRequest
	2, // 4: billing.v1.BillingService.GenerateInvoice:input_type -> billing.v1.GenerateInvoiceRequest
	3, // 5: billing.v1.BillingService.ApplyOvernightFee:input_type -> billing.v1.ApplyOvernightFeeRequest
	4, // 6: billing.v1.BillingService.StartBilling:output_type -> billing.v1.BillingResponse
	4, // 7: billing.v1.BillingService.CalculateFee:output_type -> billing.v1.BillingResponse
	4, // 8: billing.v1.BillingService.GenerateInvoice:output_type -> billing.v1.BillingResponse
	4, // 9: billing.v1.BillingService.ApplyOvernightFee:output_type -> billing.v1.BillingResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_billing_v1_billing_proto_init() }
func file_proto_billing_v1_billing_proto_init() {
	if File_proto_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_billing_v1_billing_proto_rawDesc), len(file_proto_billing_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_proto_billing_v1_billing_proto_depIdxs,
		MessageInfos:      file_proto_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_proto_billing_v1_billing_proto = out.File
	file_proto_billing_v1_billing_proto_goTypes = nil
	file_proto_billing_v1_billing_proto_depIdxs = nil
}
