// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.24.4
// source: presence/v1/presence.proto

package presencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PresenceService_StreamLocation_FullMethodName  = "/presence.v1.PresenceService/StreamLocation"
	PresenceService_DetectArrival_FullMethodName   = "/presence.v1.PresenceService/DetectArrival"
	PresenceService_DetectWrongSpot_FullMethodName = "/presence.v1.PresenceService/DetectWrongSpot"
	PresenceService_GetPresence_FullMethodName     = "/presence.v1.PresenceService/GetPresence"
)

// PresenceServiceClient is the client API for PresenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PresenceService handles location streaming, geofence arrival detection, and wrong-spot detection.
type PresenceServiceClient interface {
	// StreamLocation receives a stream of location updates from the driver app.
	StreamLocation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LocationUpdate, StreamLocationResponse], error)
	// DetectArrival checks if a driver has arrived within the parking geofence.
	DetectArrival(ctx context.Context, in *DetectArrivalRequest, opts ...grpc.CallOption) (*ArrivalResponse, error)
	// DetectWrongSpot checks if a driver is parked in the wrong spot.
	DetectWrongSpot(ctx context.Context, in *DetectWrongSpotRequest, opts ...grpc.CallOption) (*WrongSpotResponse, error)
	// GetPresence returns the latest known location for a reservation.
	GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*PresenceResponse, error)
}

type presenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPresenceServiceClient(cc grpc.ClientConnInterface) PresenceServiceClient {
	return &presenceServiceClient{cc}
}

func (c *presenceServiceClient) StreamLocation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LocationUpdate, StreamLocationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PresenceService_ServiceDesc.Streams[0], PresenceService_StreamLocation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LocationUpdate, StreamLocationResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PresenceService_StreamLocationClient = grpc.ClientStreamingClient[LocationUpdate, StreamLocationResponse]

func (c *presenceServiceClient) DetectArrival(ctx context.Context, in *DetectArrivalRequest, opts ...grpc.CallOption) (*ArrivalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArrivalResponse)
	err := c.cc.Invoke(ctx, PresenceService_DetectArrival_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) DetectWrongSpot(ctx context.Context, in *DetectWrongSpotRequest, opts ...grpc.CallOption) (*WrongSpotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WrongSpotResponse)
	err := c.cc.Invoke(ctx, PresenceService_DetectWrongSpot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*PresenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PresenceResponse)
	err := c.cc.Invoke(ctx, PresenceService_GetPresence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PresenceServiceServer is the server API for PresenceService service.
// All implementations must embed UnimplementedPresenceServiceServer
// for forward compatibility.
//
// PresenceService handles location streaming, geofence arrival detection, and wrong-spot detection.
type PresenceServiceServer interface {
	// StreamLocation receives a stream of location updates from the driver app.
	StreamLocation(grpc.ClientStreamingServer[LocationUpdate, StreamLocationResponse]) error
	// DetectArrival checks if a driver has arrived within the parking geofence.
	DetectArrival(context.Context, *DetectArrivalRequest) (*ArrivalResponse, error)
	// DetectWrongSpot checks if a driver is parked in the wrong spot.
	DetectWrongSpot(context.Context, *DetectWrongSpotRequest) (*WrongSpotResponse, error)
	// GetPresence returns the latest known location for a reservation.
	GetPresence(context.Context, *GetPresenceRequest) (*PresenceResponse, error)
	mustEmbedUnimplementedPresenceServiceServer()
}

// UnimplementedPresenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPresenceServiceServer struct{}

func (UnimplementedPresenceServiceServer) StreamLocation(grpc.ClientStreamingServer[LocationUpdate, StreamLocationResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamLocation not implemented")
}
func (UnimplementedPresenceServiceServer) DetectArrival(context.Context, *DetectArrivalRequest) (*ArrivalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectArrival not implemented")
}
func (UnimplementedPresenceServiceServer) DetectWrongSpot(context.Context, *DetectWrongSpotRequest) (*WrongSpotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectWrongSpot not implemented")
}
func (UnimplementedPresenceServiceServer) GetPresence(context.Context, *GetPresenceRequest) (*PresenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPresence not implemented")
}
func (UnimplementedPresenceServiceServer) mustEmbedUnimplementedPresenceServiceServer() {}
func (UnimplementedPresenceServiceServer) testEmbeddedByValue()                         {}

// UnsafePresenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PresenceServiceServer will
// result in compilation errors.
type UnsafePresenceServiceServer interface {
	mustEmbedUnimplementedPresenceServiceServer()
}

func RegisterPresenceServiceServer(s grpc.ServiceRegistrar, srv PresenceServiceServer) {
	// If the following call panics, it indicates UnimplementedPresenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PresenceService_ServiceDesc, srv)
}

func _PresenceService_StreamLocation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PresenceServiceServer).StreamLocation(&grpc.GenericServerStream[LocationUpdate, StreamLocationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PresenceService_StreamLocationServer = grpc.ClientStreamingServer[LocationUpdate, StreamLocationResponse]

func _PresenceService_DetectArrival_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectArrivalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).DetectArrival(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_DetectArrival_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).DetectArrival(ctx, req.(*DetectArrivalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_DetectWrongSpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectWrongSpotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).DetectWrongSpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_DetectWrongSpot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).DetectWrongSpot(ctx, req.(*DetectWrongSpotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_GetPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).GetPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_GetPresence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).GetPresence(ctx, req.(*GetPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PresenceService_ServiceDesc is the grpc.ServiceDesc for PresenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PresenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "presence.v1.PresenceService",
	HandlerType: (*PresenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectArrival",
			Handler:    _PresenceService_DetectArrival_Handler,
		},
		{
			MethodName: "DetectWrongSpot",
			Handler:    _PresenceService_DetectWrongSpot_Handler,
		},
		{
			MethodName: "GetPresence",
			Handler:    _PresenceService_GetPresence_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLocation",
			Handler:       _PresenceService_StreamLocation_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "presence/v1/presence.proto",
}
