// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: presence/v1/presence.proto

package presencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PresenceServiceClient is the client API for PresenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PresenceServiceClient interface {
	// StreamLocation receives a stream of location updates from the driver app.
	StreamLocation(ctx context.Context, opts ...grpc.CallOption) (PresenceService_StreamLocationClient, error)
	// DetectArrival checks if a driver has arrived within the parking geofence.
	DetectArrival(ctx context.Context, in *DetectArrivalRequest, opts ...grpc.CallOption) (*ArrivalResponse, error)
	// DetectWrongSpot checks if a driver is parked in the wrong spot.
	DetectWrongSpot(ctx context.Context, in *DetectWrongSpotRequest, opts ...grpc.CallOption) (*WrongSpotResponse, error)
	// GetPresence returns the latest known location for a reservation.
	GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*PresenceResponse, error)
}

type presenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPresenceServiceClient(cc grpc.ClientConnInterface) PresenceServiceClient {
	return &presenceServiceClient{cc}
}

func (c *presenceServiceClient) StreamLocation(ctx context.Context, opts ...grpc.CallOption) (PresenceService_StreamLocationClient, error) {
	stream, err := c.cc.NewStream(ctx, &PresenceService_ServiceDesc.Streams[0], "/presence.v1.PresenceService/StreamLocation", opts...)
	if err != nil {
		return nil, err
	}
	x := &presenceServiceStreamLocationClient{stream}
	return x, nil
}

type PresenceService_StreamLocationClient interface {
	Send(*LocationUpdate) error
	CloseAndRecv() (*StreamLocationResponse, error)
	grpc.ClientStream
}

type presenceServiceStreamLocationClient struct {
	grpc.ClientStream
}

func (x *presenceServiceStreamLocationClient) Send(m *LocationUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *presenceServiceStreamLocationClient) CloseAndRecv() (*StreamLocationResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamLocationResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *presenceServiceClient) DetectArrival(ctx context.Context, in *DetectArrivalRequest, opts ...grpc.CallOption) (*ArrivalResponse, error) {
	out := new(ArrivalResponse)
	err := c.cc.Invoke(ctx, "/presence.v1.PresenceService/DetectArrival", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) DetectWrongSpot(ctx context.Context, in *DetectWrongSpotRequest, opts ...grpc.CallOption) (*WrongSpotResponse, error) {
	out := new(WrongSpotResponse)
	err := c.cc.Invoke(ctx, "/presence.v1.PresenceService/DetectWrongSpot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*PresenceResponse, error) {
	out := new(PresenceResponse)
	err := c.cc.Invoke(ctx, "/presence.v1.PresenceService/GetPresence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PresenceServiceServer is the server API for PresenceService service.
// All implementations must embed UnimplementedPresenceServiceServer
// for forward compatibility
type PresenceServiceServer interface {
	// StreamLocation receives a stream of location updates from the driver app.
	StreamLocation(PresenceService_StreamLocationServer) error
	// DetectArrival checks if a driver has arrived within the parking geofence.
	DetectArrival(context.Context, *DetectArrivalRequest) (*ArrivalResponse, error)
	// DetectWrongSpot checks if a driver is parked in the wrong spot.
	DetectWrongSpot(context.Context, *DetectWrongSpotRequest) (*WrongSpotResponse, error)
	// GetPresence returns the latest known location for a reservation.
	GetPresence(context.Context, *GetPresenceRequest) (*PresenceResponse, error)
	mustEmbedUnimplementedPresenceServiceServer()
}

// UnimplementedPresenceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPresenceServiceServer struct {
}

func (UnimplementedPresenceServiceServer) StreamLocation(PresenceService_StreamLocationServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLocation not implemented")
}
func (UnimplementedPresenceServiceServer) DetectArrival(context.Context, *DetectArrivalRequest) (*ArrivalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectArrival not implemented")
}
func (UnimplementedPresenceServiceServer) DetectWrongSpot(context.Context, *DetectWrongSpotRequest) (*WrongSpotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectWrongSpot not implemented")
}
func (UnimplementedPresenceServiceServer) GetPresence(context.Context, *GetPresenceRequest) (*PresenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPresence not implemented")
}
func (UnimplementedPresenceServiceServer) mustEmbedUnimplementedPresenceServiceServer() {}

// UnsafePresenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PresenceServiceServer will
// result in compilation errors.
type UnsafePresenceServiceServer interface {
	mustEmbedUnimplementedPresenceServiceServer()
}

func RegisterPresenceServiceServer(s grpc.ServiceRegistrar, srv PresenceServiceServer) {
	s.RegisterService(&PresenceService_ServiceDesc, srv)
}

func _PresenceService_StreamLocation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PresenceServiceServer).StreamLocation(&presenceServiceStreamLocationServer{stream})
}

type PresenceService_StreamLocationServer interface {
	SendAndClose(*StreamLocationResponse) error
	Recv() (*LocationUpdate, error)
	grpc.ServerStream
}

type presenceServiceStreamLocationServer struct {
	grpc.ServerStream
}

func (x *presenceServiceStreamLocationServer) SendAndClose(m *StreamLocationResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *presenceServiceStreamLocationServer) Recv() (*LocationUpdate, error) {
	m := new(LocationUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PresenceService_DetectArrival_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectArrivalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).DetectArrival(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/presence.v1.PresenceService/DetectArrival",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).DetectArrival(ctx, req.(*DetectArrivalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_DetectWrongSpot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectWrongSpotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).DetectWrongSpot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/presence.v1.PresenceService/DetectWrongSpot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).DetectWrongSpot(ctx, req.(*DetectWrongSpotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_GetPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).GetPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/presence.v1.PresenceService/GetPresence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).GetPresence(ctx, req.(*GetPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PresenceService_ServiceDesc is the grpc.ServiceDesc for PresenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PresenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "presence.v1.PresenceService",
	HandlerType: (*PresenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectArrival",
			Handler:    _PresenceService_DetectArrival_Handler,
		},
		{
			MethodName: "DetectWrongSpot",
			Handler:    _PresenceService_DetectWrongSpot_Handler,
		},
		{
			MethodName: "GetPresence",
			Handler:    _PresenceService_GetPresence_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLocation",
			Handler:       _PresenceService_StreamLocation_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "presence/v1/presence.proto",
}
