// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: presence/v1/presence.proto

package presencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	FloorNumber   int32                  `protobuf:"varint,3,opt,name=floor_number,json=floorNumber,proto3" json:"floor_number,omitempty"`
	SpotNumber    int32                  `protobuf:"varint,4,opt,name=spot_number,json=spotNumber,proto3" json:"spot_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPresenceRequest) Reset() {
	*x = VerifyPresenceRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPresenceRequest) ProtoMessage() {}

func (x *VerifyPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPresenceRequest.ProtoReflect.Descriptor instead.
func (*VerifyPresenceRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyPresenceRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *VerifyPresenceRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *VerifyPresenceRequest) GetFloorNumber() int32 {
	if x != nil {
		return x.FloorNumber
	}
	return 0
}

func (x *VerifyPresenceRequest) GetSpotNumber() int32 {
	if x != nil {
		return x.SpotNumber
	}
	return 0
}

type VerifyPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPresenceResponse) Reset() {
	*x = VerifyPresenceResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPresenceResponse) ProtoMessage() {}

func (x *VerifyPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPresenceResponse.ProtoReflect.Descriptor instead.
func (*VerifyPresenceResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyPresenceResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerifyPresenceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_presence_v1_presence_proto protoreflect.FileDescriptor

const file_presence_v1_presence_proto_rawDesc = "" +
	"\n" +
	"\x1apresence/v1/presence.proto\x12\vpresence.v1\"\x9f\x01\n" +
	"\x15VerifyPresenceRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12!\n" +
	"\ffloor_number\x18\x03 \x01(\x05R\vfloorNumber\x12\x1f\n" +
	"\vspot_number\x18\x04 \x01(\x05R\n" +
	"spotNumber\"N\n" +
	"\x16VerifyPresenceResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2l\n" +
	"\x0fPresenceService\x12Y\n" +
	"\x0eVerifyPresence\x12\".presence.v1.VerifyPresenceRequest\x1a#.presence.v1.VerifyPresenceResponseB,Z*parkir-pintar/proto/presence/v1;presencev1b\x06proto3"

var (
	file_presence_v1_presence_proto_rawDescOnce sync.Once
	file_presence_v1_presence_proto_rawDescData []byte
)

func file_presence_v1_presence_proto_rawDescGZIP() []byte {
	file_presence_v1_presence_proto_rawDescOnce.Do(func() {
		file_presence_v1_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_presence_v1_presence_proto_rawDesc), len(file_presence_v1_presence_proto_rawDesc)))
	})
	return file_presence_v1_presence_proto_rawDescData
}

var file_presence_v1_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_presence_v1_presence_proto_goTypes = []any{
	(*VerifyPresenceRequest)(nil),  // 0: presence.v1.VerifyPresenceRequest
	(*VerifyPresenceResponse)(nil), // 1: presence.v1.VerifyPresenceResponse
}
var file_presence_v1_presence_proto_depIdxs = []int32{
	0, // 0: presence.v1.PresenceService.VerifyPresence:input_type -> presence.v1.VerifyPresenceRequest
	1, // 1: presence.v1.PresenceService.VerifyPresence:output_type -> presence.v1.VerifyPresenceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_presence_v1_presence_proto_init() }
func file_presence_v1_presence_proto_init() {
	if File_presence_v1_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_presence_v1_presence_proto_rawDesc), len(file_presence_v1_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_presence_v1_presence_proto_goTypes,
		DependencyIndexes: file_presence_v1_presence_proto_depIdxs,
		MessageInfos:      file_presence_v1_presence_proto_msgTypes,
	}.Build()
	File_presence_v1_presence_proto = out.File
	file_presence_v1_presence_proto_goTypes = nil
	file_presence_v1_presence_proto_depIdxs = nil
}
