// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.4
// source: presence/v1/presence.proto

package presencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationUpdate) Reset() {
	*x = LocationUpdate{}
	mi := &file_presence_v1_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationUpdate) ProtoMessage() {}

func (x *LocationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationUpdate.ProtoReflect.Descriptor instead.
func (*LocationUpdate) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{0}
}

func (x *LocationUpdate) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *LocationUpdate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationUpdate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationUpdate) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *LocationUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StreamLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLocationResponse) Reset() {
	*x = StreamLocationResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLocationResponse) ProtoMessage() {}

func (x *StreamLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLocationResponse.ProtoReflect.Descriptor instead.
func (*StreamLocationResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{1}
}

func (x *StreamLocationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DetectArrivalRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReservationId   string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Latitude        float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude       float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CenterLatitude  float64                `protobuf:"fixed64,4,opt,name=center_latitude,json=centerLatitude,proto3" json:"center_latitude,omitempty"`
	CenterLongitude float64                `protobuf:"fixed64,5,opt,name=center_longitude,json=centerLongitude,proto3" json:"center_longitude,omitempty"`
	RadiusMeters    float64                `protobuf:"fixed64,6,opt,name=radius_meters,json=radiusMeters,proto3" json:"radius_meters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DetectArrivalRequest) Reset() {
	*x = DetectArrivalRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectArrivalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectArrivalRequest) ProtoMessage() {}

func (x *DetectArrivalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectArrivalRequest.ProtoReflect.Descriptor instead.
func (*DetectArrivalRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{2}
}

func (x *DetectArrivalRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *DetectArrivalRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DetectArrivalRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DetectArrivalRequest) GetCenterLatitude() float64 {
	if x != nil {
		return x.CenterLatitude
	}
	return 0
}

func (x *DetectArrivalRequest) GetCenterLongitude() float64 {
	if x != nil {
		return x.CenterLongitude
	}
	return 0
}

func (x *DetectArrivalRequest) GetRadiusMeters() float64 {
	if x != nil {
		return x.RadiusMeters
	}
	return 0
}

type ArrivalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arrived       bool                   `protobuf:"varint,1,opt,name=arrived,proto3" json:"arrived,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	DetectedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrivalResponse) Reset() {
	*x = ArrivalResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrivalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrivalResponse) ProtoMessage() {}

func (x *ArrivalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrivalResponse.ProtoReflect.Descriptor instead.
func (*ArrivalResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{3}
}

func (x *ArrivalResponse) GetArrived() bool {
	if x != nil {
		return x.Arrived
	}
	return false
}

func (x *ArrivalResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ArrivalResponse) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

type DetectWrongSpotRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReservationId   string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Latitude        float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude       float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	SpotLatitude    float64                `protobuf:"fixed64,4,opt,name=spot_latitude,json=spotLatitude,proto3" json:"spot_latitude,omitempty"`
	SpotLongitude   float64                `protobuf:"fixed64,5,opt,name=spot_longitude,json=spotLongitude,proto3" json:"spot_longitude,omitempty"`
	ThresholdMeters float64                `protobuf:"fixed64,6,opt,name=threshold_meters,json=thresholdMeters,proto3" json:"threshold_meters,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DetectWrongSpotRequest) Reset() {
	*x = DetectWrongSpotRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectWrongSpotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectWrongSpotRequest) ProtoMessage() {}

func (x *DetectWrongSpotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectWrongSpotRequest.ProtoReflect.Descriptor instead.
func (*DetectWrongSpotRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{4}
}

func (x *DetectWrongSpotRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *DetectWrongSpotRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DetectWrongSpotRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DetectWrongSpotRequest) GetSpotLatitude() float64 {
	if x != nil {
		return x.SpotLatitude
	}
	return 0
}

func (x *DetectWrongSpotRequest) GetSpotLongitude() float64 {
	if x != nil {
		return x.SpotLongitude
	}
	return 0
}

func (x *DetectWrongSpotRequest) GetThresholdMeters() float64 {
	if x != nil {
		return x.ThresholdMeters
	}
	return 0
}

type WrongSpotResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsWrongSpot    bool                   `protobuf:"varint,1,opt,name=is_wrong_spot,json=isWrongSpot,proto3" json:"is_wrong_spot,omitempty"`
	DistanceMeters float64                `protobuf:"fixed64,2,opt,name=distance_meters,json=distanceMeters,proto3" json:"distance_meters,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WrongSpotResponse) Reset() {
	*x = WrongSpotResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WrongSpotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WrongSpotResponse) ProtoMessage() {}

func (x *WrongSpotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WrongSpotResponse.ProtoReflect.Descriptor instead.
func (*WrongSpotResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{5}
}

func (x *WrongSpotResponse) GetIsWrongSpot() bool {
	if x != nil {
		return x.IsWrongSpot
	}
	return false
}

func (x *WrongSpotResponse) GetDistanceMeters() float64 {
	if x != nil {
		return x.DistanceMeters
	}
	return 0
}

type GetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceRequest) Reset() {
	*x = GetPresenceRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRequest) ProtoMessage() {}

func (x *GetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{6}
}

func (x *GetPresenceRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type PresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	RecordedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceResponse) Reset() {
	*x = PresenceResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceResponse) ProtoMessage() {}

func (x *PresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceResponse.ProtoReflect.Descriptor instead.
func (*PresenceResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{7}
}

func (x *PresenceResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *PresenceResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PresenceResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PresenceResponse) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *PresenceResponse) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

var File_presence_v1_presence_proto protoreflect.FileDescriptor

const file_presence_v1_presence_proto_rawDesc = "" +
	"\n" +
	"\x1apresence/v1/presence.proto\x12\vpresence.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x01\n" +
	"\x0eLocationUpdate\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\x01R\baccuracy\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"0\n" +
	"\x16StreamLocationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xf0\x01\n" +
	"\x14DetectArrivalRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12'\n" +
	"\x0fcenter_latitude\x18\x04 \x01(\x01R\x0ecenterLatitude\x12)\n" +
	"\x10center_longitude\x18\x05 \x01(\x01R\x0fcenterLongitude\x12#\n" +
	"\rradius_meters\x18\x06 \x01(\x01R\fradiusMeters\"\x8f\x01\n" +
	"\x0fArrivalResponse\x12\x18\n" +
	"\aarrived\x18\x01 \x01(\bR\aarrived\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12;\n" +
	"\vdetected_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\"\xf0\x01\n" +
	"\x16DetectWrongSpotRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12#\n" +
	"\rspot_latitude\x18\x04 \x01(\x01R\fspotLatitude\x12%\n" +
	"\x0espot_longitude\x18\x05 \x01(\x01R\rspotLongitude\x12)\n" +
	"\x10threshold_meters\x18\x06 \x01(\x01R\x0fthresholdMeters\"`\n" +
	"\x11WrongSpotResponse\x12\"\n" +
	"\ris_wrong_spot\x18\x01 \x01(\bR\visWrongSpot\x12'\n" +
	"\x0fdistance_meters\x18\x02 \x01(\x01R\x0edistanceMeters\";\n" +
	"\x12GetPresenceRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"\xcc\x01\n" +
	"\x10PresenceResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\x01R\baccuracy\x12;\n" +
	"\vrecorded_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt2\xe0\x02\n" +
	"\x0fPresenceService\x12T\n" +
	"\x0eStreamLocation\x12\x1b.presence.v1.LocationUpdate\x1a#.presence.v1.StreamLocationResponse(\x01\x12P\n" +
	"\rDetectArrival\x12!.presence.v1.DetectArrivalRequest\x1a\x1c.presence.v1.ArrivalResponse\x12V\n" +
	"\x0fDetectWrongSpot\x12#.presence.v1.DetectWrongSpotRequest\x1a\x1e.presence.v1.WrongSpotResponse\x12M\n" +
	"\vGetPresence\x12\x1f.presence.v1.GetPresenceRequest\x1a\x1d.presence.v1.PresenceResponseB,Z*parkir-pintar/proto/presence/v1;presencev1b\x06proto3"

var (
	file_presence_v1_presence_proto_rawDescOnce sync.Once
	file_presence_v1_presence_proto_rawDescData []byte
)

func file_presence_v1_presence_proto_rawDescGZIP() []byte {
	file_presence_v1_presence_proto_rawDescOnce.Do(func() {
		file_presence_v1_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_presence_v1_presence_proto_rawDesc), len(file_presence_v1_presence_proto_rawDesc)))
	})
	return file_presence_v1_presence_proto_rawDescData
}

var file_presence_v1_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_presence_v1_presence_proto_goTypes = []any{
	(*LocationUpdate)(nil),         // 0: presence.v1.LocationUpdate
	(*StreamLocationResponse)(nil), // 1: presence.v1.StreamLocationResponse
	(*DetectArrivalRequest)(nil),   // 2: presence.v1.DetectArrivalRequest
	(*ArrivalResponse)(nil),        // 3: presence.v1.ArrivalResponse
	(*DetectWrongSpotRequest)(nil), // 4: presence.v1.DetectWrongSpotRequest
	(*WrongSpotResponse)(nil),      // 5: presence.v1.WrongSpotResponse
	(*GetPresenceRequest)(nil),     // 6: presence.v1.GetPresenceRequest
	(*PresenceResponse)(nil),       // 7: presence.v1.PresenceResponse
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_presence_v1_presence_proto_depIdxs = []int32{
	8, // 0: presence.v1.LocationUpdate.timestamp:type_name -> google.protobuf.Timestamp
	8, // 1: presence.v1.ArrivalResponse.detected_at:type_name -> google.protobuf.Timestamp
	8, // 2: presence.v1.PresenceResponse.recorded_at:type_name -> google.protobuf.Timestamp
	0, // 3: presence.v1.PresenceService.StreamLocation:input_type -> presence.v1.LocationUpdate
	2, // 4: presence.v1.PresenceService.DetectArrival:input_type -> presence.v1.DetectArrivalRequest
	4, // 5: presence.v1.PresenceService.DetectWrongSpot:input_type -> presence.v1.DetectWrongSpotRequest
	6, // 6: presence.v1.PresenceService.GetPresence:input_type -> presence.v1.GetPresenceRequest
	1, // 7: presence.v1.PresenceService.StreamLocation:output_type -> presence.v1.StreamLocationResponse
	3, // 8: presence.v1.PresenceService.DetectArrival:output_type -> presence.v1.ArrivalResponse
	5, // 9: presence.v1.PresenceService.DetectWrongSpot:output_type -> presence.v1.WrongSpotResponse
	7, // 10: presence.v1.PresenceService.GetPresence:output_type -> presence.v1.PresenceResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_presence_v1_presence_proto_init() }
func file_presence_v1_presence_proto_init() {
	if File_presence_v1_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_presence_v1_presence_proto_rawDesc), len(file_presence_v1_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_presence_v1_presence_proto_goTypes,
		DependencyIndexes: file_presence_v1_presence_proto_depIdxs,
		MessageInfos:      file_presence_v1_presence_proto_msgTypes,
	}.Build()
	File_presence_v1_presence_proto = out.File
	file_presence_v1_presence_proto_goTypes = nil
	file_presence_v1_presence_proto_depIdxs = nil
}
