global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "parkir-pintar-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["staging-gateway:8082"]

  - job_name: "parkir-pintar-reservation"
    metrics_path: /metrics
    static_configs:
      - targets: ["staging-reservation:8091"]

  - job_name: "parkir-pintar-search"
    metrics_path: /metrics
    static_configs:
      - targets: ["staging-search:8092"]

  - job_name: "parkir-pintar-billing"
    metrics_path: /metrics
    static_configs:
      - targets: ["staging-billing:8093"]

  - job_name: "parkir-pintar-payment"
    metrics_path: /metrics
    static_configs:
      - targets: ["staging-payment:8094"]

  - job_name: "parkir-pintar-presence"
    metrics_path: /metrics
    static_configs:
      - targets: ["staging-presence:8095"]

  - job_name: "parkir-pintar-notification"
    metrics_path: /metrics
    static_configs:
      - targets: ["staging-notification:8096"]
