apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: pirescer-parkir-pintar
data:
  DB_PORT: "5432"
  REDIS_PORT: "6379"
  NATS_URL: "nats.pirescer-parkir-pintar.svc.cluster.local:4222"
  JWT_ISSUER: "parkir-pintar"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy.pirescer-monitoring.svc.cluster.local:4319"
  ENVIRONMENT: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: pirescer-parkir-pintar
type: Opaque
stringData:
  DB_USERNAME: "CHANGE_ME"
  DB_PASSWORD: "CHANGE_ME"
  DB_HOST: "CHANGE_ME"
  DB_DATABASE: "pirescer_parkir_pintar"
  REDIS_HOST: "CHANGE_ME"
  REDIS_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME"
