// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/billing (interfaces: Usecase)
//
// Generated by this command:
//
//	mockgen -destination=internal/billing/mocks/mock_usecase.go -package=mocks parkir-pintar/internal/billing Usecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "parkir-pintar/internal/billing/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// ApplyOvernightFee mocks base method.
func (m *MockUsecase) ApplyOvernightFee(ctx context.Context, req *model.ApplyOvernightFeeRequest) (*model.BillingRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyOvernightFee", ctx, req)
	ret0, _ := ret[0].(*model.BillingRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyOvernightFee indicates an expected call of ApplyOvernightFee.
func (mr *MockUsecaseMockRecorder) ApplyOvernightFee(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyOvernightFee", reflect.TypeOf((*MockUsecase)(nil).ApplyOvernightFee), ctx, req)
}

// CalculateFee mocks base method.
func (m *MockUsecase) CalculateFee(ctx context.Context, req *model.CalculateFeeRequest) (*model.BillingRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateFee", ctx, req)
	ret0, _ := ret[0].(*model.BillingRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateFee indicates an expected call of CalculateFee.
func (mr *MockUsecaseMockRecorder) CalculateFee(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateFee", reflect.TypeOf((*MockUsecase)(nil).CalculateFee), ctx, req)
}

// GenerateInvoice mocks base method.
func (m *MockUsecase) GenerateInvoice(ctx context.Context, req *model.GenerateInvoiceRequest) (*model.BillingRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateInvoice", ctx, req)
	ret0, _ := ret[0].(*model.BillingRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateInvoice indicates an expected call of GenerateInvoice.
func (mr *MockUsecaseMockRecorder) GenerateInvoice(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateInvoice", reflect.TypeOf((*MockUsecase)(nil).GenerateInvoice), ctx, req)
}

// StartBilling mocks base method.
func (m *MockUsecase) StartBilling(ctx context.Context, req *model.StartBillingRequest) (*model.BillingRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartBilling", ctx, req)
	ret0, _ := ret[0].(*model.BillingRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartBilling indicates an expected call of StartBilling.
func (mr *MockUsecaseMockRecorder) StartBilling(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartBilling", reflect.TypeOf((*MockUsecase)(nil).StartBilling), ctx, req)
}
