// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/billing (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/billing/mocks/mock_repository.go -package=mocks parkir-pintar/internal/billing Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "parkir-pintar/internal/billing/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateBillingRecord mocks base method.
func (m *MockRepository) CreateBillingRecord(ctx context.Context, record *model.BillingRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBillingRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBillingRecord indicates an expected call of CreateBillingRecord.
func (mr *MockRepositoryMockRecorder) CreateBillingRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBillingRecord", reflect.TypeOf((*MockRepository)(nil).CreateBillingRecord), ctx, record)
}

// GetByIdempotencyKey mocks base method.
func (m *MockRepository) GetByIdempotencyKey(ctx context.Context, key string) (*model.BillingRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(*model.BillingRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdempotencyKey indicates an expected call of GetByIdempotencyKey.
func (mr *MockRepositoryMockRecorder) GetByIdempotencyKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdempotencyKey", reflect.TypeOf((*MockRepository)(nil).GetByIdempotencyKey), ctx, key)
}

// GetByReservationID mocks base method.
func (m *MockRepository) GetByReservationID(ctx context.Context, reservationID string) (*model.BillingRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReservationID", ctx, reservationID)
	ret0, _ := ret[0].(*model.BillingRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReservationID indicates an expected call of GetByReservationID.
func (mr *MockRepositoryMockRecorder) GetByReservationID(ctx, reservationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReservationID", reflect.TypeOf((*MockRepository)(nil).GetByReservationID), ctx, reservationID)
}

// UpdateBillingRecord mocks base method.
func (m *MockRepository) UpdateBillingRecord(ctx context.Context, record *model.BillingRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBillingRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBillingRecord indicates an expected call of UpdateBillingRecord.
func (mr *MockRepositoryMockRecorder) UpdateBillingRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBillingRecord", reflect.TypeOf((*MockRepository)(nil).UpdateBillingRecord), ctx, record)
}
