// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/search (interfaces: ReadModelRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/search/mocks/mock_read_model_repository.go -package=mocks parkir-pintar/internal/search ReadModelRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	search "parkir-pintar/internal/search"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReadModelRepository is a mock of ReadModelRepository interface.
type MockReadModelRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReadModelRepositoryMockRecorder
	isgomock struct{}
}

// MockReadModelRepositoryMockRecorder is the mock recorder for MockReadModelRepository.
type MockReadModelRepositoryMockRecorder struct {
	mock *MockReadModelRepository
}

// NewMockReadModelRepository creates a new mock instance.
func NewMockReadModelRepository(ctrl *gomock.Controller) *MockReadModelRepository {
	mock := &MockReadModelRepository{ctrl: ctrl}
	mock.recorder = &MockReadModelRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadModelRepository) EXPECT() *MockReadModelRepositoryMockRecorder {
	return m.recorder
}

// DeleteSpot mocks base method.
func (m *MockReadModelRepository) DeleteSpot(ctx context.Context, spotID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSpot", ctx, spotID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSpot indicates an expected call of DeleteSpot.
func (mr *MockReadModelRepositoryMockRecorder) DeleteSpot(ctx, spotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSpot", reflect.TypeOf((*MockReadModelRepository)(nil).DeleteSpot), ctx, spotID)
}

// UpsertSpot mocks base method.
func (m *MockReadModelRepository) UpsertSpot(ctx context.Context, spot search.SpotData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSpot", ctx, spot)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertSpot indicates an expected call of UpsertSpot.
func (mr *MockReadModelRepositoryMockRecorder) UpsertSpot(ctx, spot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSpot", reflect.TypeOf((*MockReadModelRepository)(nil).UpsertSpot), ctx, spot)
}
