// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/search/repository (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_repository.go -package=mocks parkir-pintar/internal/search/repository Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "parkir-pintar/internal/search/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetAvailabilityByVehicleType mocks base method.
func (m *MockRepository) GetAvailabilityByVehicleType(ctx context.Context, vehicleType string) ([]model.FloorAvailability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailabilityByVehicleType", ctx, vehicleType)
	ret0, _ := ret[0].([]model.FloorAvailability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailabilityByVehicleType indicates an expected call of GetAvailabilityByVehicleType.
func (mr *MockRepositoryMockRecorder) GetAvailabilityByVehicleType(ctx, vehicleType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailabilityByVehicleType", reflect.TypeOf((*MockRepository)(nil).GetAvailabilityByVehicleType), ctx, vehicleType)
}

// GetFloorSpots mocks base method.
func (m *MockRepository) GetFloorSpots(ctx context.Context, floorNumber int) ([]model.SpotDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFloorSpots", ctx, floorNumber)
	ret0, _ := ret[0].([]model.SpotDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFloorSpots indicates an expected call of GetFloorSpots.
func (mr *MockRepositoryMockRecorder) GetFloorSpots(ctx, floorNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFloorSpots", reflect.TypeOf((*MockRepository)(nil).GetFloorSpots), ctx, floorNumber)
}

// GetSpotByID mocks base method.
func (m *MockRepository) GetSpotByID(ctx context.Context, spotID string) (*model.SpotDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotByID", ctx, spotID)
	ret0, _ := ret[0].(*model.SpotDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpotByID indicates an expected call of GetSpotByID.
func (mr *MockRepositoryMockRecorder) GetSpotByID(ctx, spotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotByID", reflect.TypeOf((*MockRepository)(nil).GetSpotByID), ctx, spotID)
}
