// Code generated by MockGen. DO NOT EDIT.
// Source: parkir-pintar/internal/search (interfaces: Usecase)
//
// Generated by this command:
//
//	mockgen -destination=internal/search/mocks/mock_usecase.go -package=mocks parkir-pintar/internal/search Usecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	search "parkir-pintar/internal/search"
	model "parkir-pintar/internal/search/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// GetAvailability mocks base method.
func (m *MockUsecase) GetAvailability(ctx context.Context, req *model.GetAvailabilityRequest) ([]model.FloorAvailability, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailability", ctx, req)
	ret0, _ := ret[0].([]model.FloorAvailability)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailability indicates an expected call of GetAvailability.
func (mr *MockUsecaseMockRecorder) GetAvailability(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailability", reflect.TypeOf((*MockUsecase)(nil).GetAvailability), ctx, req)
}

// GetFloorMap mocks base method.
func (m *MockUsecase) GetFloorMap(ctx context.Context, req *model.GetFloorMapRequest) ([]model.SpotDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFloorMap", ctx, req)
	ret0, _ := ret[0].([]model.SpotDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFloorMap indicates an expected call of GetFloorMap.
func (mr *MockUsecaseMockRecorder) GetFloorMap(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFloorMap", reflect.TypeOf((*MockUsecase)(nil).GetFloorMap), ctx, req)
}

// GetSpotDetails mocks base method.
func (m *MockUsecase) GetSpotDetails(ctx context.Context, req *model.GetSpotDetailsRequest) (*model.SpotDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotDetails", ctx, req)
	ret0, _ := ret[0].(*model.SpotDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpotDetails indicates an expected call of GetSpotDetails.
func (mr *MockUsecaseMockRecorder) GetSpotDetails(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotDetails", reflect.TypeOf((*MockUsecase)(nil).GetSpotDetails), ctx, req)
}

// HandleSpotUpdated mocks base method.
func (m *MockUsecase) HandleSpotUpdated(ctx context.Context, spot search.SpotData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSpotUpdated", ctx, spot)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleSpotUpdated indicates an expected call of HandleSpotUpdated.
func (mr *MockUsecaseMockRecorder) HandleSpotUpdated(ctx, spot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSpotUpdated", reflect.TypeOf((*MockUsecase)(nil).HandleSpotUpdated), ctx, spot)
}
