apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: pirescer-parkir-pintar
  labels:
    app: gateway
    workload: service
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        workload: service
    spec:
      containers:
        - name: gateway
          image: ghcr.io/piresc/parkir-pintar/gateway:latest-prod
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: GRPC_RESERVATION_TARGET
              value: "reservation:9091"
            - name: GRPC_SEARCH_TARGET
              value: "search:9094"
            - name: GRPC_BILLING_TARGET
              value: "billing:9092"
            - name: GRPC_PAYMENT_TARGET
              value: "payment:9093"
            - name: GRPC_ANALYTICS_TARGET
              value: "analytics:9095"
            - name: GRPC_PRESENCE_TARGET
              value: "presence:9096"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: pirescer-parkir-pintar
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 8080
      name: http
